# German po for libgda
# Copyright (C) 2000 Free Software Foundation, Inc.
# Christian Meyer <cm@ggtt.de>, 2000.
# Kai Lahmann <kl@linuxfaqs.de>, 2000.
#
msgid ""
msgstr ""
"Project-Id-Version: libgda-0.2.3-cvs\n"
"POT-Creation-Date: 2001-01-07 13:54+0100\n"
"PO-Revision-Date: 2001-01-07 13:57+01:00\n"
"Last-Translator: Benedikt Roth <Benedikt.Roth@gmx.net>\n"
"Language-Team: German <gnome-de@gnome.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=iso-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#: lib/gda-client/gda-connection-pool.c:267
#, c-format
msgid "could not open connection to %s"
msgstr "Vebindung zu %s konnte nicht geöffnet werden"

#: lib/gda-client/gda-connection-pool.c:280
#, c-format
msgid "Data source %s not found"
msgstr "Datenquelle %s nicht gefunden"

#: lib/gda-client/gda-connection.c:234 lib/gda-client/gda-error.c:179
#, c-format
msgid "%s: The server didn't respond."
msgstr "%s: Der Server antwortet nicht."

#: lib/gda-client/gda-connection.c:238 lib/gda-client/gda-error.c:183
#, c-format
msgid "%s: An Error occured in the CORBA system."
msgstr "%s: Ein Fehler ist in dem CORBA-System aufgetreten."

#: lib/gda-client/gda-connection.c:493
#, c-format
msgid "Database '%s' not found in system configuration"
msgstr "Datenbank '%s' nicht in der Systemkonfiguration gefunden"

#: lib/gda-client/gda-connection.c:509
msgid "Could not open CORBA factory"
msgstr "CORBA-Einheit konnte nicht geöffnet werden"

#: lib/gda-client/gda-field.c:245
msgid "<NULL>"
msgstr "<NULL>"

#: lib/gda-client/gda-field.c:251 lib/gda-client/gda-field.c:253
msgid "<Unknown GDA Type(NULL)>"
msgstr "<Unbekannter GDA-Typ(NULL)>"

#: lib/gda-client/gda-field.c:266
msgid "TRUE"
msgstr "WAHR"

#: lib/gda-client/gda-field.c:267
msgid "FALSE"
msgstr "FALSCH"

#: lib/gda-common/gda-corba.c:73
#, c-format
msgid "CORBA System exception: %s"
msgstr "CORBA-System-Ausnahmefehler: %s"

#: lib/gda-common/gda-corba.c:102
msgid "True"
msgstr "Wahr"

#: lib/gda-common/gda-corba.c:102
msgid "False"
msgstr "Falsch"

#: lib/gda-common/gda-init.c:59
msgid "Attempt to initialize an already initialized client"
msgstr "Versuch, einen bereits initialisierten Client zu initialisieren"

#: lib/gda-common/gda-log.c:48
msgid "Saving log...x"
msgstr "Log...x wird gespeichert"

#. compose message
#: lib/gda-common/gda-log.c:69
msgid "ERROR: "
msgstr "Fehler:"

#: lib/gda-common/gda-log.c:69
msgid "MESSAGE: "
msgstr "Meldung:"

#: lib/gda-common/gda-thread.c:211
msgid "thread is already running"
msgstr "Thread läuft schon"

#: lib/gda-common/gda-xml-database.c:282
#, c-format
msgid "table %s already exists"
msgstr "Tabelle %s existiert schon"

#: lib/gda-common/gda-xml-database.c:446
#, c-format
msgid "%p is not a valid table"
msgstr "%p ist keine gültige Tabelle"

#: lib/gda-server/gda-server-error.c:185
msgid "Could not get pointer to server implementation"
msgstr "Pointer konnte nicht auf die Server-Implementiertung gesetzt werden"

#: lib/gda-server/gda-server-impl-connection.c:123
#: lib/gda-server/gda-server-impl-connection.c:132
#: lib/gda-server/gda-server-impl-connection.c:139
#: lib/gda-server/gda-server-impl-connection.c:148
#: lib/gda-server/gda-server-impl-connection.c:155
#: lib/gda-server/gda-server-impl-connection.c:164
#: lib/gda-server/gda-server-impl-connection.c:171
#: lib/gda-server/gda-server-impl-connection.c:180
#: lib/gda-server/gda-server-impl-recordset.c:126
#: lib/gda-server/gda-server-impl-recordset.c:135
#: lib/gda-server/gda-server-impl-recordset.c:142
#: lib/gda-server/gda-server-impl-recordset.c:157
#: lib/gda-server/gda-server-impl-recordset.c:166
#: lib/gda-server/gda-server-impl-recordset.c:173
#: lib/gda-server/gda-server-impl-recordset.c:182
#: lib/gda-server/gda-server-impl-recordset.c:189
#: lib/gda-server/gda-server-impl-recordset.c:198
#: lib/gda-server/gda-server-impl-recordset.c:205
#: lib/gda-server/gda-server-impl-recordset.c:213
#: lib/gda-server/gda-server-impl-recordset.c:222
#: lib/gda-server/gda-server-impl-recordset.c:229
#: lib/gda-server/gda-server-impl-recordset.c:237
#: lib/gda-server/gda-server-impl-recordset.c:245
#: lib/gda-server/gda-server-impl-recordset.c:273
#: lib/gda-server/gda-server-impl-recordset.c:281
#: lib/gda-server/gda-server-impl-recordset.c:289
#: lib/gda-server/gda-server-impl-recordset.c:297
#: lib/gda-server/gda-server-impl-recordset.c:305
#: lib/gda-server/gda-server-impl-recordset.c:314
#, c-format
msgid "%s not implemented"
msgstr "%s nicht implementiert"

#: lib/gda-server/gda-server-impl-connection.c:272
#, c-format
msgid "impl_GDA_Connection_open: opening connection with DSN: %s"
msgstr "impl_GDA_Connection_open: Verbindung mit DSN öffnen: %s"

#: lib/gda-server/gda-server-impl-recordset.c:407
#, c-format
msgid "%s: an error ocurred while fetching data"
msgstr "%s: Ein Fehler trat auf, während die Daten empfangen werden"

#: lib/gda-server/gda-server-impl-recordset.c:446
#, c-format
msgid "%s: length = %d"
msgstr "%s: Länge = %d"

#: lib/gda-server/gda-server-impl-recordset.c:459
#, c-format
msgid "%s: sending field description for '%s'"
msgstr "%s: Feld-Beschreibung für '%s' wird gesendet"

#: lib/gda-server/gda-server-impl.c:184
#, c-format
msgid "Starting provider %s with no implementation functions"
msgstr "Anbieter %s ohne Implementierungsfunktionen wird gestartet"

#: lib/gda-server/gda-server-impl.c:210
#: report/server/gda-report-server-main.c:120
msgid ""
"OAF doesn't know about our IID; indicates broken installation. Exiting..."
msgstr ""
"OAF weiß nichts über ihre IID; Deutet auf defekte Installation hin. "
"Abbruch..."

#: lib/gda-server/gda-server-impl.c:213
msgid ""
"Another instance of this provider is already registered with OAF. Exiting..."
msgstr ""
"Eine andere Instalz dieses Anbieters ist bereits mit OAF registriert. "
"Abbruch..."

#: lib/gda-server/gda-server-impl.c:216
msgid "Unknown error registering this provider with OAF. Exiting"
msgstr "Unbekannter Fehler beim Registrieren dieses Anbieters mit OAF. Abbruch"

#: lib/gda-server/gda-server-impl.c:220
#, c-format
msgid "Registered with ID = %s"
msgstr "Registriert mit ID = %s"

#: lib/gda-server/gda-server-impl.c:296
#, c-format
msgid "CORBA system exception %s"
msgstr "CORBA-System-Ausnahmefehler %s"

#: lib/gda-server/gda-server-impl.c:299
#, c-format
msgid "CORBA user exception: %s"
msgstr "CORBA Anwenderfehler: %s"

#: lib/gda-server/gda-server-init.c:63 lib/gda-server/gda-server-init.c:69
#, c-format
msgid "Received signal %d, shutting down"
msgstr "Signal %d wurde erhalten, Abbruch"

#: lib/gda-server/gda-server-init.c:73
#, c-format
msgid "Received signal %d. Ignoring"
msgstr "Signal %d wurde erhalten. Wird ignoriert"

#: lib/gda-server/gda-server-init.c:123
msgid "Attempt to initialize an already initialized provider"
msgstr "Versuch, einen bereits initialisierten Anbieter zu initialisieren"

#: providers/gda-interbase-server/gda-interbase-connection.c:261
#: providers/gda-ldap-server/gda-ldap-connection.c:272
#: providers/gda-mdb-server/gda-mdb-connection.c:360
#: providers/gda-mysql-server/gda-mysql-connection.c:387
#: providers/gda-odbc-server/gda-odbc-connection.c:609
#: providers/gda-odbc-server/gda-odbc-connection.c:642
#: providers/gda-oracle-server/gda-oracle-connection.c:426
#: providers/gda-postgres-server/gda-postgres-connection.c:779
#: providers/gda-sybase-server/gda-sybase-error.c:109
#, c-format
msgid "error '%s' at %s"
msgstr "Fehler '%s' bei %s"

#: providers/gda-interbase-server/gda-interbase-connection.c:266
#: providers/gda-interbase-server/gda-interbase-connection.c:267
#: providers/gda-ldap-server/gda-ldap-connection.c:277
#: providers/gda-ldap-server/gda-ldap-connection.c:278
#: providers/gda-mdb-server/gda-mdb-connection.c:364
#: providers/gda-mdb-server/gda-mdb-connection.c:365
#: providers/gda-mysql-server/gda-mysql-connection.c:391
#: providers/gda-mysql-server/gda-mysql-connection.c:392
#: providers/gda-odbc-server/gda-odbc-connection.c:611
#: providers/gda-odbc-server/gda-odbc-connection.c:612
#: providers/gda-odbc-server/gda-odbc-connection.c:644
#: providers/gda-odbc-server/gda-odbc-connection.c:645
#: providers/gda-oracle-server/gda-oracle-connection.c:431
#: providers/gda-oracle-server/gda-oracle-connection.c:432
#: providers/gda-postgres-server/gda-postgres-connection.c:786
#: providers/gda-postgres-server/gda-postgres-connection.c:787
#: providers/gda-sybase-server/gda-sybase-error.c:118
#: providers/gda-sybase-server/gda-sybase-error.c:119
msgid "Not available"
msgstr "Nicht verfügbar"

#: providers/gda-interbase-server/gda-interbase-connection.c:268
#: providers/gda-ldap-server/gda-ldap-connection.c:279
#: providers/gda-mdb-server/gda-mdb-connection.c:366
#: providers/gda-mysql-server/gda-mysql-connection.c:393
#: providers/gda-oracle-server/gda-oracle-connection.c:433
#: providers/gda-postgres-server/gda-postgres-connection.c:788
#: providers/gda-sybase-server/gda-sybase-error.c:120
msgid "error"
msgstr "Fehler"

#: providers/gda-ldap-server/main-ldap.c:69
msgid "Could not register LDAP provider implementation"
msgstr "LDAP-Anbieter Implementierung konnte nicht registriert werden"

#: providers/gda-interbase-server/gda-interbase-connection.c:260
#, c-format
msgid "Error code %ld"
msgstr "Fehlercode %ld"

#: providers/gda-interbase-server/main-interbase.c:70
msgid "Could not register INTERBASE provider implementation"
msgstr "INTERBASE-Anbieter Implementierung konnte nicht registriert werden"

#: providers/gda-mail-server/gda-mail-connection.c:108
#: providers/gda-mdb-server/gda-mdb-connection.c:224
#: providers/gda-mysql-server/gda-mysql-connection.c:251
#: providers/gda-oracle-server/gda-oracle-connection.c:295
#: providers/gda-postgres-server/gda-postgres-connection.c:511
#: providers/gda-sybase-server/gda-sybase-connection.c:269
#, c-format
msgid "Unhandled SCHEMA_QTYPE %d"
msgstr "Unbehandelter SCHEMA_QTYPE %d"

#: providers/gda-mail-server/main-mail.c:70
msgid "Could not register Mail provider implementation"
msgstr "Die Mail-Anbieter-Implementierung konnte nicht registriert werden"

#. execute command
#: providers/gda-mdb-server/gda-mdb-command.c:86
#: providers/gda-mysql-server/gda-mysql-command.c:87
#: providers/gda-sybase-server/gda-sybase-command.c:120
#, c-format
msgid "executing command '%s'"
msgstr "Befehl '%s' ansgeführt"

#: providers/gda-mdb-server/gda-mdb-command.c:88
#: providers/gda-mysql-server/gda-mysql-command.c:89
#, c-format
msgid "info '%s'"
msgstr "Info '%s'"

#: providers/gda-mdb-server/gda-mdb-connection.c:137
#: providers/gda-mysql-server/gda-mysql-connection.c:148
#, c-format
msgid ""
"%s:%d: You cannot provide a UNIX_SOCKET if you also provide either a HOST or "
"a PORT. Please remove the UNIX_SOCKET, or remove both the HOST and PORT "
"options"
msgstr ""
"%s:%d: Sie konnen keinen UNIX_SOCKET anbieten, wenn Sie auch einen PORT und "
"einen HOST angeben. Bitte entfernen Sie entweder die PORT- und die "
"HOST-Optionen, oder entfernen Sie die UNIX_SOCKET-Optionen"

#: providers/gda-mdb-server/gda-mdb-connection.c:147
#, c-format
msgid "%s:%d: You must  provide the filename with the MS Access database"
msgstr "%s%d: Sie müssen einen Dateinamen für die MS Access Datenbank"

#: providers/gda-mdb-server/gda-mdb-connection.c:152
#, c-format
msgid "Opening connection with filename=%s, user=%s, password=%s"
msgstr "Verbindung mit Dateiname=%s, Benutzer=%s, Passwort=%s wird geöffnet"

#: providers/gda-mdb-server/gda-mdb-connection.c:415
#: providers/gda-mysql-server/gda-mysql-connection.c:442
msgid "mysql_recset is NULL"
msgstr "mysql_recset ist NULL"

#: providers/gda-mdb-server/gda-mdb-connection.c:457
#: providers/gda-mysql-server/gda-mysql-connection.c:484
#: providers/gda-sybase-server/gda-sybase-connection.c:432
msgid "No table name given for SCHEMA_COLS"
msgstr "Kein Tabellenname für SCHEMA_COLS angegeben"

#: providers/gda-mdb-server/main-mdb.c:70
#: providers/gda-mysql-server/main-mysql.c:70
msgid "Could not register MySQL provider implementation"
msgstr "Die MySQL-Anbieter-Implementierung kann nicht registriert werden"

#: providers/gda-mysql-server/gda-mysql-connection.c:162
#, c-format
msgid ""
"Opening connection with user=%s, password=%s, host=%s, port=%s, "
"unix_socket=%s"
msgstr "Verbindung mit Benutzer=%s, Passwort=%s, Rechner=%s, Port=%s, Unix_Socket=%s wird geöffnet"

#: providers/gda-odbc-server/gda-odbc-connection.c:280
#, c-format
msgid "gda_odbc_connection_open_schema: Unhandled SCHEMA_QTYPE %d\n"
msgstr "gda_odbc_connection_open_schema: Unhebandelter SCHEMA_QTYPE %d\n"

#: providers/gda-odbc-server/gda-odbc-connection.c:626
#: providers/gda-odbc-server/gda-odbc-connection.c:627
#: providers/gda-odbc-server/gda-odbc-connection.c:628
#: providers/gda-odbc-server/gda-odbc-connection.c:659
#: providers/gda-odbc-server/gda-odbc-connection.c:660
#: providers/gda-odbc-server/gda-odbc-connection.c:661
msgid "no text"
msgstr "Kein Text"

#: providers/gda-odbc-server/main-odbc.c:69
msgid "Could not register ODBC provider implementation"
msgstr "Die ODBC-Anbieter-Implementierung konnte nicht registriert werden"

#: providers/gda-oracle-server/gda-oracle-command.c:185
msgid "Could not allocate statement handle"
msgstr "`Statement handle' konnte nicht erreicht werden"

#: providers/gda-oracle-server/gda-oracle-command.c:189
msgid "command object being created without associated connection"
msgstr "Befehlsobjekt erstellt, ohne eine dazugehörige Verbindung zu haben"

#: providers/gda-oracle-server/gda-oracle-command.c:220
#, c-format
msgid "Executing command '%s'"
msgstr "Befehl '%s' wird ausgeführt"

#: providers/gda-oracle-server/gda-oracle-connection.c:113
msgid "error in OCIHandleAlloc() HTYPE_SVCCTX"
msgstr "Fehler in OCIHandleAlloc() HTYPE_SVCCTX"

#: providers/gda-oracle-server/gda-oracle-connection.c:116
msgid "error in OCIHandleAlloc() HTYPE_SERVER"
msgstr "Fehler in OCIHandleAlloc() HTYPE_SERVER"

#: providers/gda-oracle-server/gda-oracle-connection.c:119
msgid "error in OCIHandleAlloc() HTYPE_ERROR"
msgstr "Fehler in OCIHandleAlloc() HTYPE_ERROR"

#: providers/gda-oracle-server/gda-oracle-connection.c:379
#, c-format
msgid "Unknown ORACLE type %ld"
msgstr "Unbekannter ORACLE Typ %ld"

#: providers/gda-oracle-server/gda-oracle-recordset.c:115
msgid "Unknown ORACLE data type in fill_field_values"
msgstr "Unbekannter ORACLE Datentyp in fill_field_values"

#: providers/gda-oracle-server/gda-oracle-recordset.c:150
msgid "recordset object being created without associated connection"
msgstr "Recordset-Objekt erstellt, ohne eine dazugehörige Verbindung zu haben"

#: providers/gda-oracle-server/main-oracle.c:69
msgid "Could not register ORACLE provider implementation"
msgstr "Die ORACLE-Anbieter-Implementiertung konnte nicht registriert werden"

#: providers/gda-postgres-server/gda-postgres-connection.c:888
#: providers/gda-postgres-server/gda-postgres-connection.c:1000
msgid "postgres_recset is NULL"
msgstr "postgres_recset ist NULL"

#: providers/gda-postgres-server/main-postgres.c:69
msgid "Could not register PostgreSQL provider implementation"
msgstr ""
"Die PostgreSQL-Anbieter-Implementiertung konnte nicht registriert werden"

#: providers/gda-sybase-server/gda-sybase-command.c:115
msgid "Connection seems to be dead"
msgstr "Die Verbindung scheint tot zu sein"

#: providers/gda-sybase-server/gda-sybase-command.c:135
msgid "Filling command structure failed\n"
msgstr "Füllen der Befehlsstruktur gescheitert\n"

#: providers/gda-sybase-server/gda-sybase-command.c:147
msgid "sending cmd failed"
msgstr "Senden von cmd gescheitert"

#: providers/gda-sybase-server/gda-sybase-command.c:154
msgid "Allocating recordset failed"
msgstr "Erreichen des Recordset gescheitert"

#: providers/gda-sybase-server/gda-sybase-command.c:164
msgid "Getting recordset userdata failed"
msgstr "Erreichen der Recordset-Benutzerdaten gescheitert"

#: providers/gda-sybase-server/gda-sybase-command.c:222
msgid "Command execution finished, all results processed"
msgstr "Befehlsausführung beendet, alle Ergebnisse abgearbeitet"

#: providers/gda-sybase-server/gda-sybase-command.c:226
msgid "Command failed"
msgstr "Befehl gescheitert"

#: providers/gda-sybase-server/gda-sybase-command.c:230
msgid "Execution of resultless command succeeded"
msgstr "Ausführen des ergebnisslosen Befehls gescheitert"

#: providers/gda-sybase-server/gda-sybase-command.c:246
#, c-format
msgid "ct_results() returned %x"
msgstr "ct_results() gab %x zurück"

#: providers/gda-sybase-server/gda-sybase-command.c:256
msgid "No further results, command completly succeeded."
msgstr "Keine weiteren Ergebnisse, Befehl erfolgreich beendet."

#: providers/gda-sybase-server/gda-sybase-command.c:260
msgid "An error occured during command execution."
msgstr "Ein Fehler trat beim Ausführen des Befehls auf."

#: providers/gda-sybase-server/gda-sybase-command.c:267
msgid "Cmd execution returned unknown result, may be an error"
msgstr ""
"Ausführen des Befehls hat ein unbekanntes Ergebnis zurückgegeben, "
"möglicherweise ein Fehler"

#: providers/gda-sybase-server/gda-sybase-command.c:280
msgid "No data returned, freeing recordset structure"
msgstr "Keine Daten zurückgegeben, die Struktur wird gelöscht"

#: providers/gda-sybase-server/gda-sybase-command.c:311
#: providers/gda-sybase-server/gda-sybase-command.c:323
msgid "Freeing command structure failed"
msgstr "Löschen der Befehls-Struktur gescheitert"

#: providers/gda-sybase-server/gda-sybase-connection.c:149
msgid "Error allocating error structure"
msgstr "Fehler beim Erreichen der Fehlerstruktur"

#: providers/gda-sybase-server/gda-sybase-connection.c:157
msgid "Not enough memory for sybase_Connection"
msgstr "Nicht genug Speicher für sybase_Connection"

#: providers/gda-sybase-server/gda-sybase-connection.c:422
#, c-format
msgid "schema_cols: table_name '%s'"
msgstr "schema_cols: table_name '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:438
msgid "Could not allocate command structure"
msgstr "Befehlsstruktur konnte nicht erreicht werden"

#: providers/gda-sybase-server/gda-sybase-connection.c:460
msgid "Could not allocate enough memory for query"
msgstr "Es konnte nicht genug Speicher für die Anfrage reserviert werden"

#: providers/gda-sybase-server/gda-sybase-connection.c:474
msgid "Could not get recordset in schema_cols"
msgstr "Recordset in schema_cols konnte nicht erreicht werden"

#: providers/gda-sybase-server/gda-sybase-connection.c:506
#: providers/gda-sybase-server/gda-sybase-connection.c:583
#, c-format
msgid "schema_tables: table name = '%s'"
msgstr "schema_tables: Tabellenname = '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:514
#: providers/gda-sybase-server/gda-sybase-connection.c:591
#, c-format
msgid "schema_tables: table_schema = '%s'"
msgstr "schema_tables: table_schema = '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:519
#, c-format
msgid "schema_procedures: proc_catalog = '%s' UNUSED!\n"
msgstr "schema_procedures: proc_catalog = '%s' UNGENUTZT!\n"

#: providers/gda-sybase-server/gda-sybase-connection.c:523
#, c-format
msgid "schema_procs: invalid constraint type %d"
msgstr "schema_procs: Ungültiger Konstantentyp %d"

#: providers/gda-sybase-server/gda-sybase-connection.c:533
msgid "Could not allocate cmd structure"
msgstr "Die Befehlsstruktur konnte nicht erreicht werden"

#: providers/gda-sybase-server/gda-sybase-connection.c:596
#, c-format
msgid "schema_procedures: proc_catalog = '%s' UNUSED!"
msgstr "schema_procedures: proc_catalog = '%s' UNGENUTZT!"

#: providers/gda-sybase-server/gda-sybase-connection.c:600
#, c-format
msgid "schema_tables: invalid constraint type %d"
msgstr "schema_tables: Ungültiger Konstantentyp %d"

#: providers/gda-sybase-server/gda-sybase-connection.c:661
#, c-format
msgid "Invalid or unsupported constraint type: %d"
msgstr "Ungültiger oder nicht unterstützter Konstantentyp: %d"

#: providers/gda-sybase-server/gda-sybase-connection.c:702
msgid "Could not allocate Gda_ServerCommand"
msgstr "Gda_ServerCommand konnte nicht erreicht werden"

#: providers/gda-sybase-server/gda-sybase-connection.c:732
#: providers/gda-sybase-server/gda-sybase-connection.c:737
#, c-format
msgid "connection status: %x"
msgstr "Verbindungsstatus: %x"

#: providers/gda-sybase-server/gda-sybase-connection.c:733
#, c-format
msgid "return code: %x"
msgstr "Rückgabewert: %x"

#: providers/gda-sybase-server/gda-sybase-connection.c:770
msgid "attempting reconnection"
msgstr "Verbindung wird erneut versucht"

#: providers/gda-sybase-server/gda-sybase-connection.c:909
#, c-format
msgid "Reconnected to '%s'"
msgstr "Verbunden mit '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:911
#, c-format
msgid "Connected to %s"
msgstr "Verbunden mit '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:919
#, c-format
msgid "Selected database '%s'"
msgstr "Gewählte Datenbank '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:948
#, c-format
msgid "%s: Could not allocate cmd structure"
msgstr "%s: Die Befehlsstruktur konnte nicht erreicht werden"

#: providers/gda-sybase-server/gda-sybase-connection.c:957
#, c-format
msgid "%s: Could not allocate memory for cmd string"
msgstr "%s: Speicher für den Befehlsstring konnte nicht alloziiert werden"

#: providers/gda-sybase-server/gda-sybase-connection.c:970
#, c-format
msgid "%s: ct_command failed"
msgstr "%s: ct_command gescheitert"

#: providers/gda-sybase-server/gda-sybase-connection.c:979
#, c-format
msgid "%s: sending command failed"
msgstr "%s: Senden des Befehls gescheitert"

#: providers/gda-sybase-server/gda-sybase-connection.c:990
#, c-format
msgid "%s: selecting database failed"
msgstr "%s: Auswählen der Datenbank gescheitert"

#: providers/gda-sybase-server/gda-sybase-connection.c:1008
#, c-format
msgid "%s: use command failed"
msgstr "%s: use-Befehl gescheitert"

#: providers/gda-sybase-server/gda-sybase-connection.c:1035
msgid "Could not allocate locale structure"
msgstr "Die lokale Struktur kann nicht erreicht werden"

#: providers/gda-sybase-server/gda-sybase-connection.c:1041
#, c-format
msgid "Could not set locale to '%s'"
msgstr "Lokale Struktur konnte nicht auf '%s' gesetzt werden"

#: providers/gda-sybase-server/gda-sybase-connection.c:1047
#, c-format
msgid "Could not configure locale to be '%s'"
msgstr ""
"Die lokale Struktur konnte nicht so eingestellt werden, dass sie '%s' ist"

#: providers/gda-sybase-server/gda-sybase-connection.c:1052
msgid "Could not drop locale structure"
msgstr "Die lokale Struktur konnte nicht gelöscht werden"

#: providers/gda-sybase-server/gda-sybase-connection.c:1065
#, c-format
msgid "Fatal error: %s\n"
msgstr "Schwerer Fehler: %s\n"

#: providers/gda-sybase-server/gda-sybase-error.c:65
#, c-format
msgid "gda_sybase_error_make(%p,%p,%p,%p)"
msgstr "gda_sybase_error_make(%p,%p,%p,%p)"

#: providers/gda-sybase-server/gda-sybase-error.c:74
#, c-format
msgid "No error flag ist set, though %s is called. This may be a bug."
msgstr ""
"Kein Fehlercode angegeben, obwohl %s aufgerufen wurde. Dies könnte ein "
"Fehler sein."

#: providers/gda-sybase-server/gda-sybase-error.c:138
msgid "cs_diag() initialized"
msgstr "cs_diag() initialisiert"

#: providers/gda-sybase-server/gda-sybase-error.c:141
msgid "Could not initialize cs_diag()"
msgstr "cs_diag() konnte nicht initialisiert werden"

#: providers/gda-sybase-server/gda-sybase-error.c:148
msgid "ct_diag() initialized"
msgstr "ct_diag() initialisiert"

#: providers/gda-sybase-server/gda-sybase-error.c:151
msgid "Could not initialize ct_diag()"
msgstr " ct_diag() konnte nicht initialisiert werden"

#: providers/gda-sybase-server/gda-sybase-error.c:185
#, c-format
msgid "%s could not find server implementation"
msgstr "%s konnte die Server-Implementierung nicht finden"

#: providers/gda-sybase-server/gda-sybase-error.c:191
#, c-format
msgid "%s could not get cnc userdata"
msgstr "%s konnte die cnc-Benutzerdaten nicht erhalten"

#: providers/gda-sybase-server/gda-sybase-error.c:203
msgid "Could not get # of messages"
msgstr "Die Anahl der Meldungen konnte nicht erhalten werden"

#: providers/gda-sybase-server/gda-sybase-error.c:208
#, c-format
msgid "%d ctlib messages to fetch"
msgstr "%d ctlib-Meldungen zu empfangen"

#: providers/gda-sybase-server/gda-sybase-error.c:210
#, c-format
msgid "%d ctlib message to fetch"
msgstr "ctlib-Meldung %d zu empfangen"

#: providers/gda-sybase-server/gda-sybase-error.c:246
msgid "error is nullpointer in gda_sybase_messages_handle"
msgstr "Fehler ist Nullzeiger in gda_sybase_messages_handle"

#: providers/gda-sybase-server/gda-sybase-error.c:271
#: providers/gda-sybase-server/gda-sybase-error.c:338
#: providers/gda-sybase-server/gda-sybase-error.c:381
msgid "Could not get # of server messages"
msgstr "Die Anzahl der Server-Meldungen konnte nicht erhalten werden"

#: providers/gda-sybase-server/gda-sybase-error.c:279
#, c-format
msgid "Fetching %d client messages"
msgstr "%d Client-Meldungen werden geholt"

#: providers/gda-sybase-server/gda-sybase-error.c:281
#, c-format
msgid "Fetching %d client message"
msgstr "Client-Meldung %d wird geholt"

#: providers/gda-sybase-server/gda-sybase-error.c:290
#, c-format
msgid "Could not get client msg # %d"
msgstr "Die Client-Meldungen %d konnte nicht empfangen werden"

#: providers/gda-sybase-server/gda-sybase-error.c:306
msgid "Could not get # of client messages"
msgstr "Die Anzahl der Client-Meldungen konnte nicht ermittelt werden"

#: providers/gda-sybase-server/gda-sybase-error.c:314
msgid "Could not clear client messages"
msgstr "Client-Meldungen konnte nicht gelöscht werden"

#: providers/gda-sybase-server/gda-sybase-error.c:346
#, c-format
msgid "Fetching %d server messages"
msgstr "%d Server-Meldungen werden geholt"

#: providers/gda-sybase-server/gda-sybase-error.c:348
#, c-format
msgid "Fetching %d server message"
msgstr "Server-Meldung %d werden geholt"

#: providers/gda-sybase-server/gda-sybase-error.c:357
#, c-format
msgid "Could not get server msg # %d"
msgstr "Die Server-Meldung %d konnte nicht empfangen werden"

#: providers/gda-sybase-server/gda-sybase-error.c:389
msgid "Could not clear server messages"
msgstr "Die Server-Meldungen konnte nicht gelöscht werden"

#: providers/gda-sybase-server/gda-sybase-error.c:411
#: providers/gda-sybase-server/gda-sybase-error.c:447
msgid "Could not get # of cslib messages"
msgstr "Die Anzahl der cslib-Meldungen konnte nicht empfangen werden"

#: providers/gda-sybase-server/gda-sybase-error.c:419
#, c-format
msgid "Fetching %d cslib messages"
msgstr "%d cslib-Meldungen werden geholt"

#: providers/gda-sybase-server/gda-sybase-error.c:421
#, c-format
msgid "Fetching %d cslib message"
msgstr "cslib-Meldung %d wird geholt"

#: providers/gda-sybase-server/gda-sybase-error.c:431
#, c-format
msgid "Could not get cslib msg # %d"
msgstr "Die cslib-Meldung %d konnte nicht empfagen werden"

#: providers/gda-sybase-server/gda-sybase-error.c:455
msgid "Could not clear cslib messages"
msgstr "Die cslib-Meldungen konnte nicht gelöscht werden"

#: providers/gda-sybase-server/gda-sybase-error.c:587
msgid "Server message:"
msgstr "Server-Nachricht:"

#: providers/gda-sybase-server/gda-sybase-error.c:596
msgid "Client message:"
msgstr "Client-Nachricht:"

#: providers/gda-sybase-server/gda-sybase-error.c:603
msgid "CS-Library error:"
msgstr "CS-Bibliotheks-Fehler:"

#: providers/gda-sybase-server/gda-sybase-recordset.c:152
#, c-format
msgid "fetch error at row %d"
msgstr "Fehler in Zeile %d "

#: providers/gda-sybase-server/gda-sybase-recordset.c:159
#, c-format
msgid "CS_END_DATA on row %d; canceling"
msgstr "CS_END_DATA in Zeile %d; Abbruch"

#: providers/gda-sybase-server/gda-sybase-recordset.c:168
#, c-format
msgid "%s: Error (%d)"
msgstr "%s: Fehler (%d)"

#: providers/gda-sybase-server/gda-sybase-recordset.c:343
msgid "Failed fetching # of columns"
msgstr "Die Anzahl der Spalten konnte nicht geholt werden"

#: providers/gda-sybase-server/gda-sybase-recordset.c:349
#, c-format
msgid "Counted %d columns"
msgstr "%d Spalten gezählt"

#: providers/gda-sybase-server/gda-sybase-recordset.c:356
#, c-format
msgid "%s could not allocate datafmt info"
msgstr "%s konnte `datafmt info' nicht erreichen"

#: providers/gda-sybase-server/gda-sybase-recordset.c:366
#, c-format
msgid "%s could not allocate data fields"
msgstr "%s konnte die Datenfelder nicht erreichen"

#: providers/gda-sybase-server/gda-sybase-recordset.c:384
#, c-format
msgid "ct_describe on col # %d"
msgstr "ct_describe in Zeile %d"

#: providers/gda-sybase-server/gda-sybase-recordset.c:391
#, c-format
msgid "ct_describe on col # %d failed"
msgstr "ct_describe in Zeile %d gescheitert"

#: providers/gda-sybase-server/gda-sybase-recordset.c:397
#, c-format
msgid "ct_describe(%d): '%s', %d (%s)"
msgstr "ct_describe(%d): '%s', %d (%s)"

#: providers/gda-sybase-server/gda-sybase-recordset.c:406
msgid "could not allocate data holder"
msgstr "Der Datenhalter konnte nicht erreicht werden"

#: providers/gda-sybase-server/gda-sybase-recordset.c:416
msgid "could not ct_bind data holder to column"
msgstr "`data holder' konnte nicht an Spalte gebunden (ct_bind) werden"

#: providers/gda-sybase-server/gda-sybase-recordset.c:423
msgid "illegal type detected, aborting"
msgstr "Unzulässiger Typ entdeckt, Abbruch"

#: providers/gda-sybase-server/gda-sybase-recordset.c:429
msgid "could not allocate field"
msgstr "Das Feld konnte nicht erreicht werden"

#: providers/gda-sybase-server/main-sybase.c:74
msgid "Could not register gda-sybase provider implementation"
msgstr ""
"Die gda-sybase-Anbieter-Implementiertung konnte nicht registriert werden"

#: report/gda-report-engine.c:87
#, c-format
msgid "CORBA exception unloading report engine: %s"
msgstr "CORBA-Ausnahme, Berichtsmodul wird entfernt: %s"

#: report/server/gda-report-server-main.c:43
#: report/server/gda-report-server-main.c:50
#, c-format
msgid "Received signal %d, shutting down."
msgstr "Signal %d wurde erhalten, Abbruch."

#: report/server/gda-report-server-main.c:54
#, c-format
msgid "Received signal %d, shutting down cleanly"
msgstr "Signal %d wurde erhalten, sauberer Herunterfahren"

#: report/server/gda-report-server-main.c:96
msgid "Failed to initialize OAF: please mail bug report to OAF maintainers"
msgstr ""
"OAF konnte nicht initialisiert werden: Bitte berichten Sie diesen Fehler an "
"die OAF-Entwickler"

#: report/server/gda-report-server-main.c:106
msgid "Could not activate report engine"
msgstr "Die Berichts-Maschine konnte nicht aktiviert werden"

#: report/server/gda-report-server-main.c:123
msgid ""
"Another instance of the report engine is already registered with OAF. "
"Exiting..."
msgstr ""
"Eine andere Instalz dieses Anbieters ist bereits mit OAF registriert. "
"Beenden..."

#: report/server/gda-report-server-main.c:126
msgid "Unknown error registering report engine with OAF. Exiting"
msgstr "Unbekannter Fehler beim Registrieren dieses Anbieters mit OAF. Beenden"

#: report/server/gda-report-server-main.c:130
#, c-format
msgid "Registered report engine with ID = %s"
msgstr "Berichtsmodul registriert mit ID = %s"

#: tools/gda-run.c:34
msgid "database name"
msgstr "Datenbankname"

#: tools/gda-run.c:34
msgid "DATABASE"
msgstr "DATENBANK"

#: tools/gda-run.c:35
msgid "user name"
msgstr "Benutzername"

#: tools/gda-run.c:35
msgid "USER-NAME"
msgstr "BENUTZERNAME"

#: tools/gda-run.c:36
msgid "password"
msgstr "Passwort"

#: tools/gda-run.c:36
msgid "PASSWORD"
msgstr "PASSWORT"

#: tools/gda-run.c:37
msgid "file name"
msgstr "Dateiname"

#: tools/gda-run.c:37
msgid "FILE-NAME"
msgstr "DATEINAME"

#: tools/gda-run.c:109
#, c-format
msgid "%s: misconfigured DSN entry"
msgstr "%s: Fehlkonfigurierter DSN Eintrag"

#: tools/gda-run.c:124
#, c-format
msgid "%s: data source '%s' not found\n"
msgstr "%s: Datenquelle '%s' nicht gefunden\n"

#~ msgid "%s: not implemented"
#~ msgstr "%s: nicht implemeniert"

#~ msgid "Fetchong %d cslib message"
#~ msgstr "cslib-Meldung %d werden geholt"
