# Libgda Spanish Translation
# Copyright (C) YEAR Free Software Foundation, Inc.
# Rodrigo Moya <rmoya@chez.com>, 1999.
# Ismael Olea <olea@hispafuentes.com>, 2000
# Carlos Perelló Marín <carlos@gnome-db.org>, 2001
# Antonio de la Torre <adltorre@terra.es>, 2001
#
msgid ""
msgstr ""
"Project-Id-Version: gnome-db \n"
"POT-Creation-Date: 2001-05-27 14:38+0200\n"
"PO-Revision-Date: 2001-03-14 01:06+0100\n"
"Last-Translator: Antonio de la Torre <adltorre@terra.es>\n"
"Language-Team: Spanish <es@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=iso-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#: lib/gda-client/gda-connection-pool.c:337
#, c-format
msgid "could not open connection to %s"
msgstr "No se pudo abrir la conexión con %s"

#: lib/gda-client/gda-connection-pool.c:345
#, c-format
msgid "Data source %s not found"
msgstr "No se encontró la fuentes de datos %s"

#: lib/gda-client/gda-connection.c:235 lib/gda-client/gda-error.c:179
#, c-format
msgid "%s: The server didn't respond."
msgstr "%s: El servidor no contesta."

#: lib/gda-client/gda-connection.c:239 lib/gda-client/gda-error.c:183
#, c-format
msgid "%s: An Error occured in the CORBA system."
msgstr "%s: Ha ocurrido un error en el sistema CORBA."

#: lib/gda-client/gda-connection.c:511
#, c-format
msgid "Database '%s' not found in system configuration"
msgstr "La base de datos '%s' no se ha encontrado en el sistema"

#: lib/gda-client/gda-connection.c:526
msgid "Could not open CORBA factory"
msgstr "No se ha podido abrir la \"factory\" de CORBA"

#: lib/gda-client/gda-field.c:245
msgid "<NULL>"
msgstr "<VACÍO>"

#: lib/gda-client/gda-field.c:251 lib/gda-client/gda-field.c:253
msgid "<Unknown GDA Type(NULL)>"
msgstr "<Tipo GDA desconocido (VACÍO)>"

#: lib/gda-client/gda-field.c:266
msgid "TRUE"
msgstr "SI"

#: lib/gda-client/gda-field.c:267
msgid "FALSE"
msgstr "NO"

#: lib/gda-common/gda-corba.c:75
#, c-format
msgid "CORBA System exception: %s"
msgstr "Excepción CORBA del sistema: %s"

#: lib/gda-common/gda-corba.c:105
msgid "True"
msgstr "Verdad"

#: lib/gda-common/gda-corba.c:105
msgid "False"
msgstr "Falso"

#: lib/gda-common/gda-init.c:59
msgid "Attempt to initialize an already initialized client"
msgstr "Se ha intentado inicializar un cliente que ya lo estaba"

#: lib/gda-common/gda-log.c:48
msgid "Saving log...x"
msgstr "Guardando el log...x"

#. compose message
#: lib/gda-common/gda-log.c:69
msgid "ERROR: "
msgstr "ERROR: "

#: lib/gda-common/gda-log.c:69
msgid "MESSAGE: "
msgstr "MENSAJE: "

#: lib/gda-common/gda-thread.c:211
msgid "thread is already running"
msgstr "el hilo ya se está ejecutando"

#: lib/gda-common/gda-xml-database.c:286
#, c-format
msgid "table %s already exists"
msgstr "la tabla %s ya existe"

#: lib/gda-common/gda-xml-database.c:450
#, c-format
msgid "%p is not a valid table"
msgstr "%p no es una tabla válida"

#: lib/gda-server/gda-server-error.c:185
msgid "Could not get pointer to server implementation"
msgstr "No se puede obtener un puntero a la implementación del servidor"

#: lib/gda-server/gda-server-impl-connection.c:122
#: lib/gda-server/gda-server-impl-connection.c:131
#: lib/gda-server/gda-server-impl-connection.c:138
#: lib/gda-server/gda-server-impl-connection.c:147
#: lib/gda-server/gda-server-impl-connection.c:154
#: lib/gda-server/gda-server-impl-connection.c:163
#: lib/gda-server/gda-server-impl-connection.c:170
#: lib/gda-server/gda-server-impl-connection.c:179
#: lib/gda-server/gda-server-impl-recordset.c:126
#: lib/gda-server/gda-server-impl-recordset.c:135
#: lib/gda-server/gda-server-impl-recordset.c:142
#: lib/gda-server/gda-server-impl-recordset.c:157
#: lib/gda-server/gda-server-impl-recordset.c:166
#: lib/gda-server/gda-server-impl-recordset.c:173
#: lib/gda-server/gda-server-impl-recordset.c:182
#: lib/gda-server/gda-server-impl-recordset.c:189
#: lib/gda-server/gda-server-impl-recordset.c:198
#: lib/gda-server/gda-server-impl-recordset.c:205
#: lib/gda-server/gda-server-impl-recordset.c:213
#: lib/gda-server/gda-server-impl-recordset.c:222
#: lib/gda-server/gda-server-impl-recordset.c:229
#: lib/gda-server/gda-server-impl-recordset.c:237
#: lib/gda-server/gda-server-impl-recordset.c:245
#: lib/gda-server/gda-server-impl-recordset.c:273
#: lib/gda-server/gda-server-impl-recordset.c:281
#: lib/gda-server/gda-server-impl-recordset.c:289
#: lib/gda-server/gda-server-impl-recordset.c:297
#: lib/gda-server/gda-server-impl-recordset.c:305
#: lib/gda-server/gda-server-impl-recordset.c:314
#, c-format
msgid "%s not implemented"
msgstr "%s no está implementado"

#: lib/gda-server/gda-server-impl-connection.c:269
#, c-format
msgid "impl_GDA_Connection_open: opening connection with DSN: %s"
msgstr "impl_GDA_Connection_open: abriendo una conexión con DSN: %s"

#: lib/gda-server/gda-server-impl-recordset.c:402
#, c-format
msgid "%s: an error ocurred while fetching data"
msgstr "%s: ha ocurrido un error mientras se obtenían datos"

#: lib/gda-server/gda-server-impl.c:197
#, c-format
msgid "Starting provider %s with no implementation functions"
msgstr "Iniciando el proveedor %s sin funciones de implementación"

#: lib/gda-server/gda-server-impl.c:223
#: report/server/gda-report-server-main.c:113
msgid ""
"OAF doesn't know about our IID; indicates broken installation. Exiting..."
msgstr ""
"OAF no conoce nuestro IID; indica que la instalación es incorrecta. "
"Saliendo..."

#: lib/gda-server/gda-server-impl.c:226
msgid ""
"Another instance of this provider is already registered with OAF. Exiting..."
msgstr "Este proveedor ya ha sido registrado previamente en OAF. Saliendo..."

#: lib/gda-server/gda-server-impl.c:229
msgid "Unknown error registering this provider with OAF. Exiting"
msgstr "Error desconocido al registrar este proveedor en OAF. Saliendo"

#: lib/gda-server/gda-server-impl.c:233
#, c-format
msgid "Registered with ID = %s"
msgstr "Registrado con ID = %s"

#: lib/gda-server/gda-server-impl.c:312
#, c-format
msgid "CORBA system exception %s"
msgstr "Excepción CORBA del sistema %s"

#: lib/gda-server/gda-server-impl.c:315
#, c-format
msgid "CORBA user exception: %s"
msgstr "Excepción CORBA de usuario: %s"

#: lib/gda-server/gda-server-init.c:63 lib/gda-server/gda-server-init.c:69
#, c-format
msgid "Received signal %d, shutting down"
msgstr "Recibida la señal %d, cerrando"

#: lib/gda-server/gda-server-init.c:73
#, c-format
msgid "Received signal %d. Ignoring"
msgstr "Recibida la señal %d. Ignorándola"

#: lib/gda-server/gda-server-init.c:123
msgid "Attempt to initialize an already initialized provider"
msgstr "Se ha intentado inicializar un proveedor que ya se había inicializado"

#: providers/gda-ldap-server/GNOME_GDA_Provider_LDAP.oaf.in.h:1
msgid "GDA Datasource Access for LDAP"
msgstr "Fuente de datos GDA para LDAP"

#: providers/gda-interbase-server/gda-interbase-connection.c:273
#: providers/gda-ldap-server/gda-ldap-connection.c:284
#: providers/gda-mdb-server/gda-mdb-connection.c:372
#: providers/gda-mysql-server/gda-mysql-connection.c:370
#: providers/gda-odbc-server/gda-odbc-connection.c:621
#: providers/gda-odbc-server/gda-odbc-connection.c:654
#: providers/gda-oracle-server/gda-oracle-connection.c:438
#: providers/gda-postgres-server/gda-postgres-connection.c:743
#: providers/gda-sybase-server/gda-sybase-error.c:115
#: providers/gda-tds-server/gda-tds-error.c:114
#, c-format
msgid "error '%s' at %s"
msgstr "error '%s' en %s"

#: providers/gda-interbase-server/gda-interbase-connection.c:278
#: providers/gda-interbase-server/gda-interbase-connection.c:279
#: providers/gda-ldap-server/gda-ldap-connection.c:289
#: providers/gda-ldap-server/gda-ldap-connection.c:290
#: providers/gda-mdb-server/gda-mdb-connection.c:376
#: providers/gda-mdb-server/gda-mdb-connection.c:377
#: providers/gda-mysql-server/gda-mysql-connection.c:374
#: providers/gda-mysql-server/gda-mysql-connection.c:375
#: providers/gda-odbc-server/gda-odbc-connection.c:623
#: providers/gda-odbc-server/gda-odbc-connection.c:624
#: providers/gda-odbc-server/gda-odbc-connection.c:656
#: providers/gda-odbc-server/gda-odbc-connection.c:657
#: providers/gda-oracle-server/gda-oracle-connection.c:443
#: providers/gda-oracle-server/gda-oracle-connection.c:444
#: providers/gda-postgres-server/gda-postgres-connection.c:750
#: providers/gda-postgres-server/gda-postgres-connection.c:751
#: providers/gda-primebase-server/gda-primebase-connection.c:363
#: providers/gda-primebase-server/gda-primebase-connection.c:364
#: providers/gda-sybase-server/gda-sybase-error.c:124
#: providers/gda-sybase-server/gda-sybase-error.c:125
#: providers/gda-tds-server/gda-tds-error.c:123
#: providers/gda-tds-server/gda-tds-error.c:124
msgid "Not available"
msgstr "No está disponible"

#: providers/gda-interbase-server/gda-interbase-connection.c:280
#: providers/gda-ldap-server/gda-ldap-connection.c:291
#: providers/gda-mdb-server/gda-mdb-connection.c:378
#: providers/gda-mysql-server/gda-mysql-connection.c:376
#: providers/gda-oracle-server/gda-oracle-connection.c:445
#: providers/gda-postgres-server/gda-postgres-connection.c:752
#: providers/gda-primebase-server/gda-primebase-connection.c:365
#: providers/gda-sybase-server/gda-sybase-error.c:126
#: providers/gda-tds-server/gda-tds-error.c:125
msgid "error"
msgstr "error"

#: providers/gda-ldap-server/main-ldap.c:71
msgid "Could not register LDAP provider implementation"
msgstr "No se ha podido registrar la implementación del proveedor LDAP"

#: providers/gda-interbase-server/GNOME_GDA_Provider_InterBase.oaf.in.h:1
msgid "GDA Datasource Access for Interbase"
msgstr "Fuente de datos GDA para Interbase"

#: providers/gda-interbase-server/gda-interbase-connection.c:272
#, c-format
msgid "Error code %ld"
msgstr "Código de error %ld"

#: providers/gda-interbase-server/main-interbase.c:72
msgid "Could not register INTERBASE provider implementation"
msgstr "No se ha podido registrar la implementación del proveedor INTERBASE"

#: providers/gda-mail-server/GNOME_GDA_Provider_Mail.oaf.in.h:1
msgid "GDA Datasource Access for Mail"
msgstr "Fuente de datos GDA para Correo"

#: providers/gda-mail-server/gda-mail-connection.c:108
#: providers/gda-mdb-server/gda-mdb-connection.c:224
#: providers/gda-mysql-server/gda-mysql-connection.c:239
#: providers/gda-oracle-server/gda-oracle-connection.c:295
#: providers/gda-postgres-server/gda-postgres-connection.c:477
#: providers/gda-sybase-server/gda-sybase-connection.c:283
#: providers/gda-tds-server/gda-tds-connection.c:288
#, c-format
msgid "Unhandled SCHEMA_QTYPE %d"
msgstr "SCHEMA_QTYPE %d no manejado"

#: providers/gda-mail-server/main-mail.c:72
msgid "Could not register Mail provider implementation"
msgstr "No se ha podido registrar la implementación del proveedor de Correo"

#: providers/gda-mdb-server/GNOME_GDA_Provider_MDB.oaf.in.h:1
msgid "GDA Datasource Access for MDB (MS Access) files"
msgstr "Fuente de datos GDA para archivos MDB (MS Access)"

#. execute command
#: providers/gda-mdb-server/gda-mdb-command.c:86
#: providers/gda-mysql-server/gda-mysql-command.c:103
#: providers/gda-sybase-server/gda-sybase-command.c:132
#: providers/gda-tds-server/gda-tds-command.c:120
#, c-format
msgid "executing command '%s'"
msgstr "ejecutando el comando '%s'"

#: providers/gda-mdb-server/gda-mdb-command.c:88
#: providers/gda-mysql-server/gda-mysql-command.c:105
#, c-format
msgid "info '%s'"
msgstr "info '%s'"

#: providers/gda-mdb-server/gda-mdb-connection.c:137
#: providers/gda-mysql-server/gda-mysql-connection.c:140
#, c-format
msgid ""
"%s:%d: You cannot provide a UNIX_SOCKET if you also provide either a HOST or "
"a PORT. Please remove the UNIX_SOCKET, or remove both the HOST and PORT "
"options"
msgstr ""
"%s:%d: No puede facilitar un UNIX_SOCKET si también da un HOST o un PORT. "
"Elimine el UNIX_SOCKET, o elimine las opciones HOST y el PORT"

#: providers/gda-mdb-server/gda-mdb-connection.c:147
#, c-format
msgid "%s:%d: You must  provide the filename with the MS Access database"
msgstr ""
"%s:%d: Debe de facilitar el nombre del archivo de la base de datos de MS "
"Access"

#: providers/gda-mdb-server/gda-mdb-connection.c:152
#, c-format
msgid "Opening connection with filename=%s, user=%s, password=%s"
msgstr "Abriendo conexión con  archivo=%s, usuario=%s, contraseña=%s"

#: providers/gda-mdb-server/gda-mdb-connection.c:427
#: providers/gda-mysql-server/gda-mysql-connection.c:421
msgid "mysql_recset is NULL"
msgstr "mysql_recset está VACÍO"

#: providers/gda-mdb-server/gda-mdb-connection.c:469
#: providers/gda-mysql-server/gda-mysql-connection.c:460
#: providers/gda-sybase-server/gda-sybase-connection.c:458
#: providers/gda-tds-server/gda-tds-connection.c:457
msgid "No table name given for SCHEMA_COLS"
msgstr "No ha se ha dado el nombre de una tabla para SCHEMA_COLS"

#: providers/gda-mdb-server/main-mdb.c:72
#: providers/gda-mysql-server/main-mysql.c:72
msgid "Could not register MySQL provider implementation"
msgstr "No se ha podido registrar la implementación del proveedor MySQL"

#: providers/gda-mysql-server/GNOME_GDA_Provider_MySQL.oaf.in.h:1
msgid "GDA Datasource Access for MySQL"
msgstr "Fuente de datos GDA para MySQL"

#: providers/gda-mysql-server/gda-mysql-connection.c:153
#, c-format
msgid ""
"Opening connection with user=%s, password=%s, host=%s, port=%s, unix_socket=%"
"s"
msgstr ""
"Abriendo conexión con el usuario=%s, contraseña=%s, sistema=%s, puerto=%s, "
"unix_socket=%s"

#: providers/gda-odbc-server/GNOME_GDA_Provider_ODBC.oaf.in.h:1
msgid "GDA Datasource Access for ODBC"
msgstr "Acceso de Fuente de datos GDA para ODBC"

#: providers/gda-odbc-server/gda-odbc-connection.c:280
#, c-format
msgid "gda_odbc_connection_open_schema: Unhandled SCHEMA_QTYPE %d\n"
msgstr "gda_odbc_connection_open_schema: SCHEMA_QTYPE %d no manejado\n"

#: providers/gda-odbc-server/gda-odbc-connection.c:638
#: providers/gda-odbc-server/gda-odbc-connection.c:639
#: providers/gda-odbc-server/gda-odbc-connection.c:640
#: providers/gda-odbc-server/gda-odbc-connection.c:671
#: providers/gda-odbc-server/gda-odbc-connection.c:672
#: providers/gda-odbc-server/gda-odbc-connection.c:673
msgid "no text"
msgstr "ningún texto"

#: providers/gda-odbc-server/main-odbc.c:71
msgid "Could not register ODBC provider implementation"
msgstr "No pudo registrase la implementación del proveedor ODBC"

#: providers/gda-oracle-server/GNOME_GDA_Provider_Oracle.oaf.in.h:1
msgid "GDA Datasource Access for Oracle"
msgstr "Fuente de datos GDA para Oracle"

#: providers/gda-oracle-server/gda-oracle-command.c:185
msgid "Could not allocate statement handle"
msgstr "No pudo localizarse el manejador de orden"

#: providers/gda-oracle-server/gda-oracle-command.c:189
msgid "command object being created without associated connection"
msgstr "objeto comando creándose sin conexión asociada"

#: providers/gda-oracle-server/gda-oracle-command.c:220
#, c-format
msgid "Executing command '%s'"
msgstr "Ejecutando comando '%s'"

#: providers/gda-oracle-server/gda-oracle-connection.c:113
msgid "error in OCIHandleAlloc() HTYPE_SVCCTX"
msgstr "error en OCIHandleAlloc() HTYPE_SVCCTX"

#: providers/gda-oracle-server/gda-oracle-connection.c:116
msgid "error in OCIHandleAlloc() HTYPE_SERVER"
msgstr "error en OCIHandleAlloc() HTYPE_SERVER"

#: providers/gda-oracle-server/gda-oracle-connection.c:119
msgid "error in OCIHandleAlloc() HTYPE_ERROR"
msgstr "error en OCIHandleAlloc() HTYPE_ERROR"

#: providers/gda-oracle-server/gda-oracle-connection.c:379
#, c-format
msgid "Unknown ORACLE type %ld"
msgstr "Tipo Oracle %ld desconocido"

#: providers/gda-oracle-server/gda-oracle-recordset.c:115
msgid "Unknown ORACLE data type in fill_field_values"
msgstr "Tipo de datos Oracle desconocido en fill_field_values"

#: providers/gda-oracle-server/gda-oracle-recordset.c:150
msgid "recordset object being created without associated connection"
msgstr "Objeto recordset creándose sin conexión asociada"

#: providers/gda-oracle-server/main-oracle.c:71
msgid "Could not register ORACLE provider implementation"
msgstr "No pudo registrarse la implementación del proveedor de Oracle"

#: providers/gda-postgres-server/GNOME_GDA_Provider_Postgres.oaf.in.h:1
msgid "GDA Datasource Access for Postgres"
msgstr "Acceso de la Fuente de Datos GDA para Postgres"

#: providers/gda-postgres-server/gda-postgres-connection.c:849
#: providers/gda-postgres-server/gda-postgres-connection.c:957
msgid "postgres_recset is NULL"
msgstr "postgres_recset está VACÍO"

#: providers/gda-postgres-server/main-postgres.c:71
msgid "Could not register PostgreSQL provider implementation"
msgstr "No pudo registrarse la implementación del proveedor PostgreSQL"

#: providers/gda-sybase-server/GNOME_GDA_Provider_Sybase.oaf.in.h:1
msgid "GDA Datasource Access for Sybase"
msgstr "Acceso de la Fuente de Datos GDA para Sybase"

#.      gda_server_error_make(error, 0, cnc, "connection seems to be dead");
#: providers/gda-sybase-server/gda-sybase-command.c:127
#: providers/gda-tds-server/gda-tds-command.c:116
msgid "Connection seems to be dead"
msgstr "La conexión parece que ha terminado"

#: providers/gda-sybase-server/gda-sybase-command.c:146
#: providers/gda-tds-server/gda-tds-command.c:131
msgid "Filling command structure failed\n"
msgstr "Error al rellenar la estructura de comando\n"

#: providers/gda-sybase-server/gda-sybase-command.c:158
#: providers/gda-tds-server/gda-tds-command.c:139
msgid "sending cmd failed"
msgstr "error al enviar cmd"

#: providers/gda-sybase-server/gda-sybase-command.c:165
#: providers/gda-tds-server/gda-tds-command.c:146
msgid "Allocating recordset failed"
msgstr "Error al adjudicar recordset"

#: providers/gda-sybase-server/gda-sybase-command.c:175
#: providers/gda-tds-server/gda-tds-command.c:154
msgid "Getting recordset userdata failed"
msgstr "Error al obtener datos de usuario de recordset"

#: providers/gda-sybase-server/gda-sybase-command.c:233
#: providers/gda-tds-server/gda-tds-command.c:207
msgid "Command execution finished, all results processed"
msgstr "Ejecución de comando finalizada. todos los resultados procesados"

#: providers/gda-sybase-server/gda-sybase-command.c:237
#: providers/gda-tds-server/gda-tds-command.c:211
msgid "Command failed"
msgstr "Comando fallido"

#: providers/gda-sybase-server/gda-sybase-command.c:241
#: providers/gda-tds-server/gda-tds-command.c:215
msgid "Execution of resultless command succeeded"
msgstr "Ejecución correcta de comando resultless"

#: providers/gda-sybase-server/gda-sybase-command.c:257
#: providers/gda-tds-server/gda-tds-command.c:231
#, c-format
msgid "ct_results() returned %x"
msgstr "ct_results() devolvió %x"

#: providers/gda-sybase-server/gda-sybase-command.c:267
#: providers/gda-tds-server/gda-tds-command.c:241
msgid "No further results, command completly succeeded."
msgstr "No más resultados, comando correcto"

#: providers/gda-sybase-server/gda-sybase-command.c:271
#: providers/gda-tds-server/gda-tds-command.c:245
msgid "An error occured during command execution."
msgstr "Un error ha ocurrido durante la ejecución del comando."

#: providers/gda-sybase-server/gda-sybase-command.c:278
#: providers/gda-tds-server/gda-tds-command.c:249
msgid "Cmd execution returned unknown result, may be an error"
msgstr ""
"La ejecución de Cmd devolvió un resultado desconocido, puede ser un error"

#: providers/gda-sybase-server/gda-sybase-command.c:291
#: providers/gda-tds-server/gda-tds-command.c:259
msgid "No data returned, freeing recordset structure"
msgstr "No hay datos devueltos, liberando estructura recordset"

#: providers/gda-sybase-server/gda-sybase-command.c:322
#: providers/gda-sybase-server/gda-sybase-command.c:334
#: providers/gda-tds-server/gda-tds-command.c:289
#: providers/gda-tds-server/gda-tds-command.c:297
msgid "Freeing command structure failed"
msgstr "Error al liberar la estructura de comando"

#: providers/gda-sybase-server/gda-sybase-connection.c:171
#, fuzzy
msgid "Not enough memory for sybase_Connection"
msgstr "No hay suficiente memoria para primebase_Error structure."

#: providers/gda-sybase-server/gda-sybase-connection.c:448
#: providers/gda-tds-server/gda-tds-connection.c:447
#, c-format
msgid "schema_cols: table_name '%s'"
msgstr "schema_cols: table_name '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:464
#: providers/gda-tds-server/gda-tds-connection.c:463
msgid "Could not allocate command structure"
msgstr "No pudo asignarse estructura de comando"

#: providers/gda-sybase-server/gda-sybase-connection.c:486
#: providers/gda-tds-server/gda-tds-connection.c:485
msgid "Could not allocate enough memory for query"
msgstr "No pudo asignarse suficiente memoria para la búsqueda"

#. 		gda_server_error_make(error, NULL, cnc, __PRETTY_FUNCTION__);
#: providers/gda-sybase-server/gda-sybase-connection.c:500
#: providers/gda-tds-server/gda-tds-connection.c:499
msgid "Could not get recordset in schema_cols"
msgstr "No pudo obtenerse recordset en schema_cols"

#: providers/gda-sybase-server/gda-sybase-connection.c:549
#: providers/gda-tds-server/gda-tds-connection.c:548
#, c-format
msgid "schema_procs: invalid constraint type %d"
msgstr "schema_procs: restricción no válida tipo %d"

#: providers/gda-sybase-server/gda-sybase-connection.c:559
#: providers/gda-tds-server/gda-tds-connection.c:558
msgid "Could not allocate cmd structure"
msgstr "No pudo asignarse estructura cmd"

#: providers/gda-sybase-server/gda-sybase-connection.c:626
#: providers/gda-tds-server/gda-tds-connection.c:625
#, c-format
msgid "schema_tables: invalid constraint type %d"
msgstr "schema_tables: restricción no válida tipo %d"

#: providers/gda-sybase-server/gda-sybase-connection.c:687
#: providers/gda-tds-server/gda-tds-connection.c:686
#, c-format
msgid "Invalid or unsupported constraint type: %d"
msgstr "Tipo de restricción no válida o no soportada: %d"

#: providers/gda-sybase-server/gda-sybase-connection.c:728
#: providers/gda-tds-server/gda-tds-connection.c:727
msgid "Could not allocate GdaServerCommand"
msgstr "No pudo asignarse GdaServerCommand"

#: providers/gda-sybase-server/gda-sybase-connection.c:758
#: providers/gda-sybase-server/gda-sybase-connection.c:763
#: providers/gda-tds-server/gda-tds-connection.c:757
#: providers/gda-tds-server/gda-tds-connection.c:762
#, c-format
msgid "connection status: %x"
msgstr "Estado de conexión: %x"

#: providers/gda-sybase-server/gda-sybase-connection.c:759
#: providers/gda-tds-server/gda-tds-connection.c:758
#, c-format
msgid "return code: %x"
msgstr "código devuelto: %x"

#: providers/gda-sybase-server/gda-sybase-connection.c:796
#: providers/gda-tds-server/gda-tds-connection.c:793
msgid "attempting reconnection"
msgstr "intentando reconexión"

#: providers/gda-sybase-server/gda-sybase-connection.c:935
#, c-format
msgid "Reconnected to '%s'"
msgstr "Reconectado a '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:937
#: providers/gda-tds-server/gda-tds-connection.c:898
#, c-format
msgid "Connected to %s"
msgstr "Conectado a %s"

#: providers/gda-sybase-server/gda-sybase-connection.c:945
#: providers/gda-tds-server/gda-tds-connection.c:908
#, c-format
msgid "Selected database '%s'"
msgstr "Base de datos '%s'seleccionada"

#: providers/gda-sybase-server/gda-sybase-connection.c:974
#: providers/gda-tds-server/gda-tds-connection.c:933
#, c-format
msgid "%s: Could not allocate cmd structure"
msgstr "%s: No pudo asignarse estructura cmd"

#: providers/gda-sybase-server/gda-sybase-connection.c:983
#: providers/gda-tds-server/gda-tds-connection.c:942
#, c-format
msgid "%s: Could not allocate memory for cmd string"
msgstr "%s: No pudo asignarse memoria para la serie cmd"

#: providers/gda-sybase-server/gda-sybase-connection.c:996
#: providers/gda-tds-server/gda-tds-connection.c:952
#, c-format
msgid "%s: ct_command failed"
msgstr "%s: ct_command fallido"

#: providers/gda-sybase-server/gda-sybase-connection.c:1005
#: providers/gda-tds-server/gda-tds-connection.c:961
#, c-format
msgid "%s: sending command failed"
msgstr "%s: error al enviar comando"

#: providers/gda-sybase-server/gda-sybase-connection.c:1016
#, c-format
msgid "%s: selecting database failed"
msgstr "%s: error al seleccionar base de datos"

#: providers/gda-sybase-server/gda-sybase-connection.c:1034
#, c-format
msgid "%s: use command failed"
msgstr "%s: error de comando uso"

#: providers/gda-sybase-server/gda-sybase-connection.c:1061
#: providers/gda-tds-server/gda-tds-connection.c:1023
msgid "Could not allocate locale structure"
msgstr "No pudo asignarse estructura local"

#: providers/gda-sybase-server/gda-sybase-connection.c:1067
#: providers/gda-tds-server/gda-tds-connection.c:1029
#, c-format
msgid "Could not set locale to '%s'"
msgstr "No pudo ubicar local para '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:1073
#: providers/gda-tds-server/gda-tds-connection.c:1035
#, c-format
msgid "Could not configure locale to be '%s'"
msgstr "No pudo configurar local para ser '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:1078
#: providers/gda-tds-server/gda-tds-connection.c:1040
msgid "Could not drop locale structure"
msgstr "No pudo darse de baja la estructura local"

#: providers/gda-sybase-server/gda-sybase-connection.c:1091
#: providers/gda-tds-server/gda-tds-connection.c:1053
#, c-format
msgid "Fatal error: %s\n"
msgstr "Error fatal: %s\n"

#: providers/gda-sybase-server/gda-sybase-error.c:71
#, c-format
msgid "gda_sybase_error_make(%p,%p,%p,%p)"
msgstr "gda_sybase_error_make(%p,%p,%p,%p)"

#: providers/gda-sybase-server/gda-sybase-error.c:80
#: providers/gda-tds-server/gda-tds-error.c:78
#, c-format
msgid "No error flag ist set, though %s is called. This may be a bug."
msgstr ""
"Ninguna señal de error está fijada, sin embargo %s está llamado. Esto puede "
"ser una fallo"

#: providers/gda-sybase-server/gda-sybase-error.c:144
msgid "cs_diag() initialized"
msgstr "cs_diag() iniciado"

#: providers/gda-sybase-server/gda-sybase-error.c:147
msgid "Could not initialize cs_diag()"
msgstr "No pudo iniciarse cs_diag()"

#: providers/gda-sybase-server/gda-sybase-error.c:154
msgid "ct_diag() initialized"
msgstr "ct_diag() iniciado"

#: providers/gda-sybase-server/gda-sybase-error.c:157
msgid "Could not initialize ct_diag()"
msgstr "No pudo iniciarse ct_diag()"

#: providers/gda-sybase-server/gda-sybase-error.c:191
#, c-format
msgid "%s could not find server implementation"
msgstr "%s no pudo encontrar la implementación del servidor"

#: providers/gda-sybase-server/gda-sybase-error.c:197
#, c-format
msgid "%s could not get cnc userdata"
msgstr "%s no pudo obtener datos de usuario cnc"

#: providers/gda-sybase-server/gda-sybase-error.c:209
msgid "Could not get # of messages"
msgstr "No pudo obtener # de mensajes"

#: providers/gda-sybase-server/gda-sybase-error.c:214
#, c-format
msgid "%d ctlib messages to fetch"
msgstr "%d mensajes ctlib para retomar"

#: providers/gda-sybase-server/gda-sybase-error.c:216
#, c-format
msgid "%d ctlib message to fetch"
msgstr "%d mensaje ctlib para retomar"

#: providers/gda-sybase-server/gda-sybase-error.c:252
msgid "error is nullpointer in gda_sybase_messages_handle"
msgstr "el error no tiene indicador en gda_sybase_messages_handle"

#: providers/gda-sybase-server/gda-sybase-error.c:277
#: providers/gda-sybase-server/gda-sybase-error.c:344
#: providers/gda-sybase-server/gda-sybase-error.c:387
msgid "Could not get # of server messages"
msgstr "No pudo obtenerse # mensajes del servidor"

#: providers/gda-sybase-server/gda-sybase-error.c:285
#, c-format
msgid "Fetching %d client messages"
msgstr "Retomando %d mensajes del cliente"

#: providers/gda-sybase-server/gda-sybase-error.c:287
#, c-format
msgid "Fetching %d client message"
msgstr "Retomando %d mensaje del cliente"

#: providers/gda-sybase-server/gda-sybase-error.c:296
#, c-format
msgid "Could not get client msg # %d"
msgstr "No pudo obtenerse mensaje # %d del cliente"

#: providers/gda-sybase-server/gda-sybase-error.c:312
msgid "Could not get # of client messages"
msgstr "No pudo obtenerse # mensajes del cliente"

#: providers/gda-sybase-server/gda-sybase-error.c:320
msgid "Could not clear client messages"
msgstr "No pudo vaciarse los mensajes del cliente"

#: providers/gda-sybase-server/gda-sybase-error.c:352
#, c-format
msgid "Fetching %d server messages"
msgstr "Retomando %d mensajes del servidor"

#: providers/gda-sybase-server/gda-sybase-error.c:354
#, c-format
msgid "Fetching %d server message"
msgstr "Retomando %d mensajes del servidor"

#: providers/gda-sybase-server/gda-sybase-error.c:363
#, c-format
msgid "Could not get server msg # %d"
msgstr "No pudo obtenerse mensaje # %d del servidor"

#: providers/gda-sybase-server/gda-sybase-error.c:395
msgid "Could not clear server messages"
msgstr "No pudo vaciarse los mensajes del servidor"

#: providers/gda-sybase-server/gda-sybase-error.c:417
#: providers/gda-sybase-server/gda-sybase-error.c:453
msgid "Could not get # of cslib messages"
msgstr "No pudo obtenerse # mensajes cslib"

#: providers/gda-sybase-server/gda-sybase-error.c:425
#, c-format
msgid "Fetching %d cslib messages"
msgstr "Retomando %d mensajes cslib"

#: providers/gda-sybase-server/gda-sybase-error.c:427
#, c-format
msgid "Fetching %d cslib message"
msgstr "Retomando %d mensaje cslib"

#: providers/gda-sybase-server/gda-sybase-error.c:437
#, c-format
msgid "Could not get cslib msg # %d"
msgstr "No pudo obtenerse mensaje # %d cslib"

#: providers/gda-sybase-server/gda-sybase-error.c:461
msgid "Could not clear cslib messages"
msgstr "No pudo vaciarse los mensajes cslib"

#: providers/gda-sybase-server/gda-sybase-error.c:593
#: providers/gda-tds-server/gda-tds-error.c:257
msgid "Server message:"
msgstr "Mensaje del servidor:"

#: providers/gda-sybase-server/gda-sybase-error.c:602
#: providers/gda-tds-server/gda-tds-error.c:266
msgid "Client message:"
msgstr "Mensaje del cliente:"

#: providers/gda-sybase-server/gda-sybase-error.c:609
#: providers/gda-tds-server/gda-tds-error.c:273
msgid "CS-Library error:"
msgstr "Error CS-Library:"

#: providers/gda-sybase-server/gda-sybase-recordset.c:158
#: providers/gda-tds-server/gda-tds-recordset.c:155
#, c-format
msgid "fetch error at row %d"
msgstr "Retomar error en la fila %d"

#: providers/gda-sybase-server/gda-sybase-recordset.c:165
#: providers/gda-tds-server/gda-tds-recordset.c:162
#, c-format
msgid "CS_END_DATA on row %d; canceling"
msgstr "CS_END_DATA en la fila %d; cancelando"

#: providers/gda-sybase-server/gda-sybase-recordset.c:174
#: providers/gda-tds-server/gda-tds-recordset.c:169
#, c-format
msgid "%s: Error (%d)"
msgstr "%s: Error (%d)"

#: providers/gda-sybase-server/gda-sybase-recordset.c:349
#: providers/gda-tds-server/gda-tds-recordset.c:342
msgid "Failed fetching # of columns"
msgstr "Error retomando # de columnas"

#: providers/gda-sybase-server/gda-sybase-recordset.c:355
#: providers/gda-tds-server/gda-tds-recordset.c:349
#, c-format
msgid "Counted %d columns"
msgstr "contadas %d columnas"

#: providers/gda-sybase-server/gda-sybase-recordset.c:362
#: providers/gda-tds-server/gda-tds-recordset.c:356
#, c-format
msgid "%s could not allocate datafmt info"
msgstr "%s no pudo asignar información datafmt"

#: providers/gda-sybase-server/gda-sybase-recordset.c:372
#: providers/gda-tds-server/gda-tds-recordset.c:366
#, c-format
msgid "%s could not allocate data fields"
msgstr "%s no pudo asignar campos de datos"

#: providers/gda-sybase-server/gda-sybase-recordset.c:390
#: providers/gda-tds-server/gda-tds-recordset.c:384
#, c-format
msgid "ct_describe on col # %d"
msgstr "ct_describe en la columna # %d"

#: providers/gda-sybase-server/gda-sybase-recordset.c:397
#: providers/gda-tds-server/gda-tds-recordset.c:391
#, c-format
msgid "ct_describe on col # %d failed"
msgstr "Error ct_describe en la columna # %d"

#: providers/gda-sybase-server/gda-sybase-recordset.c:403
#: providers/gda-tds-server/gda-tds-recordset.c:397
#, c-format
msgid "ct_describe(%d): '%s', %d (%s)"
msgstr "ct_describe(%d): '%s', %d (%s)"

#: providers/gda-sybase-server/gda-sybase-recordset.c:412
#: providers/gda-tds-server/gda-tds-recordset.c:406
msgid "could not allocate data holder"
msgstr "no pudo asignarse sustento de datos"

#: providers/gda-sybase-server/gda-sybase-recordset.c:422
#: providers/gda-tds-server/gda-tds-recordset.c:416
msgid "could not ct_bind data holder to column"
msgstr "no pudo asignarse sustento de datos ct_bind para la columna"

#: providers/gda-sybase-server/gda-sybase-recordset.c:429
#: providers/gda-tds-server/gda-tds-recordset.c:423
msgid "illegal type detected, aborting"
msgstr "tipo ilegal detectado, abortando"

#: providers/gda-sybase-server/gda-sybase-recordset.c:435
#: providers/gda-tds-server/gda-tds-recordset.c:429
msgid "could not allocate field"
msgstr "No pudo asignarse campo"

#: providers/gda-sybase-server/main-sybase.c:76
msgid "Could not register gda-sybase provider implementation"
msgstr "No pudo registrarse implementación de proveedor gda-sybase"

#: providers/gda-primebase-server/GNOME_GDA_Provider_Primebase.oaf.in.h:1
msgid "GDA Datasource Access for primebase"
msgstr "Acceso de Fuente de datos GDA para primebase"

#: providers/gda-primebase-server/gda-primebase-connection.c:158
#, c-format
msgid "Could not connect to '%s@%s:%s' with connparm '%s'"
msgstr "No se pudo conectar a '%s@%s:%s' con connparm: '%s'"

#: providers/gda-primebase-server/gda-primebase-connection.c:162
#, c-format
msgid "%2ld: Connected to '%s@%s:%s' with connparm: '%s'"
msgstr "%2ld: Conectado a '%s@%s:%s' con connparm: '%s'"

#: providers/gda-primebase-server/gda-primebase-connection.c:168
msgid "Could not get PBIConnectionInfo(), disconnecting"
msgstr "No se pudo obtener PBIConnectionInfo(), desconectando"

#: providers/gda-primebase-server/gda-primebase-connection.c:172
#, c-format
msgid "%2ld: ConInfo: '%s@%s', Cl v%x, Srv '%s' v%x, Brand '%s'"
msgstr "%2ld: ConInfo: '%s@%s', Cl v%x, Srv '%s' v%x, Brand '%s'"

#: providers/gda-primebase-server/gda-primebase-connection.c:376
msgid "Not enough memory for primebase_Error structure."
msgstr "No hay suficiente memoria para primebase_Error structure."

#: providers/gda-primebase-server/gda-primebase-connection.c:383
#, c-format
msgid "%2ld: ERROR: %ld (%ld) : %s.\n"
msgstr "%2ld: ERROR: %ld (%ld) : %s.\n"

#: providers/gda-primebase-server/main-primebase.c:70
msgid "Could not register PRIMEBASE provider implementation"
msgstr "No se pudo registrarse implementación de proveedor PRIMEBASE"

#: providers/gda-tds-server/GNOME_GDA_Provider_TDS.oaf.in.h:1
msgid "GDA Datasource Access for Sybase/MS SQL"
msgstr "Acceso a la Fuente de Datos GDA para Sybase/MS SQL"

#: providers/gda-tds-server/gda-tds-connection.c:167
#, fuzzy
msgid "Not enough memory for tds_Connection"
msgstr "No hay suficiente memoria para primebase_Error structure."

#. Fixme: replace "dummy" with buf when CS_GET CS_SERVERNAME works
#: providers/gda-tds-server/gda-tds-connection.c:896
#, c-format
msgid "Reconnected to %s"
msgstr "Reconectado a %s"

#: providers/gda-tds-server/gda-tds-error.c:69
#, c-format
msgid "gda_tds_error_make(%p,%p,%p,%p)"
msgstr "gda_tds_error_make(%p,%p,%p,%p)"

#: providers/gda-tds-server/main-tds.c:76
msgid "Could not register gda-tds provider implementation"
msgstr "No se pudo registrar la implementación del proveedor gda-tds"

#: report/gda-report-engine.c:209
#, c-format
msgid "CORBA exception unloading report engine: %s"
msgstr "Motor de informe de descarga de excepción CORBA: %s"

#: report/server/GNOME_GDA_Report.oaf.in.h:1
msgid "GDA Distributed Report Engine"
msgstr "Motor de Informe Distribuido GDA"

#: report/server/gda-report-server-main.c:41
#: report/server/gda-report-server-main.c:48
#, c-format
msgid "Received signal %d, shutting down."
msgstr "Recibida señal %d, cerrando"

#: report/server/gda-report-server-main.c:52
#, c-format
msgid "Received signal %d, shutting down cleanly"
msgstr "Recibida señal %d, cerrando limpiamente"

#: report/server/gda-report-server-main.c:92
msgid "Failed to initialize OAF: please mail bug report to OAF maintainers"
msgstr ""
"Error a iniciar OAF: por favor, envía un mensaje de fallo a los mantenedores "
"de OAF"

#: report/server/gda-report-server-main.c:101
msgid "Could not activate report engine"
msgstr "No pudo activarse el motor de informe"

#: report/server/gda-report-server-main.c:116
msgid ""
"Another instance of the report engine is already registered with OAF. "
"Exiting..."
msgstr ""
"Otra instancia de motor de informe ha sido ya registrada con OAF. Saliendo..."

#: report/server/gda-report-server-main.c:119
msgid "Unknown error registering report engine with OAF. Exiting"
msgstr "Error desconocido registrando motor de informe con OAF. Saliendo"

#: report/server/gda-report-server-main.c:123
#, c-format
msgid "Registered report engine with ID = %s"
msgstr "Motor de informe registrado con ID = %s"

#: tools/gda-run.c:109
#, c-format
msgid "%s: misconfigured DSN entry"
msgstr "%s: Entrada DSN desconfigurada"

#: tools/gda-run.c:124
#, c-format
msgid "%s: data source '%s' not found\n"
msgstr "%s: fuente de datos '%s' no encontrada\n"

#~ msgid "%s: length = %d"
#~ msgstr "%s: longitud = %d"

#~ msgid "%s: sending field description for '%s'"
#~ msgstr "%s: enviando la descripción del campo '%s'"

#~ msgid "schema_tables: table name = '%s'"
#~ msgstr "schema_tables: nombre de tabla = '%s'"

#~ msgid "schema_tables: table_schema = '%s'"
#~ msgstr "schema_tables: table_schema = '%s'"

#~ msgid "schema_procedures: proc_catalog = '%s' UNUSED!\n"
#~ msgstr "schema_procedures: proc_catalog = ¡'%s' NO USADO!\n"

#~ msgid "schema_procedures: proc_catalog = '%s' UNUSED!"
#~ msgstr "schema_procedures: proc_catalog = ¡'%s' NO USADO!"

#~ msgid "database name"
#~ msgstr "nombre de base de datos"

#~ msgid "DATABASE"
#~ msgstr "DATABASE"

#~ msgid "user name"
#~ msgstr "nombre de usuario"

#~ msgid "USER-NAME"
#~ msgstr "NOMBRE-DE-USUARIO"

#~ msgid "password"
#~ msgstr "contraseña"

#~ msgid "PASSWORD"
#~ msgstr "CONTRASEÑA"

#~ msgid "file name"
#~ msgstr "nombre de archivo"

#~ msgid "FILE-NAME"
#~ msgstr "NOMBRE-DE-ARCHIVO"
