# Galician translation of libgda.
# Copyright (C) 2000 Jesús Bravo Álvarez.
# Jesús Bravo Álvarez <jba@pobox.com>, 2000.
#
# Proxecto Trasno - Adaptación do software libre á lingua galega:  Se desexas
# colaborar connosco, podes atopar máis información en http://trasno.gpul.org
#
# First Version: 2000-04-29 12:07+0200
#
msgid ""
msgstr ""
"Project-Id-Version: libgda\n"
"POT-Creation-Date: 2001-11-18 18:46+0100\n"
"PO-Revision-Date: 2000-10-29 15:03+0100\n"
"Last-Translator: Jesús Bravo Álvarez <jba@pobox.com>\n"
"Language-Team: Galician <trasno@ceu.fi.udc.es>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=iso-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#: lib/gda-client/gda-connection-pool.c:268
#, c-format
msgid "could not open connection to %s"
msgstr "non foi posible abrir unha conexión a %s"

#: lib/gda-client/gda-connection-pool.c:281
#, c-format
msgid "Data source %s not found"
msgstr "Fonte de datos %s non atopada"

#: lib/gda-client/gda-connection.c:448
#, c-format
msgid "Database '%s' not found in system configuration"
msgstr "Base de datos '%s' non atopada na configuración do sistema"

#: lib/gda-client/gda-connection.c:452 lib/gda-client/gda-connection.c:469
msgid "[GDA Client Library]"
msgstr ""

#: lib/gda-client/gda-connection.c:468
msgid "Could not open CORBA factory"
msgstr "Non foi posible abri-la fábrica CORBA"

#: lib/gda-client/gda-field.c:243 lib/gda-client/gda-field.c:298
#: lib/gda-client/gda-field.c:307
#: providers/gda-mysql-server/gda-mysql-recordset.c:197
msgid "<NULL>"
msgstr "<NULL>"

#: lib/gda-client/gda-field.c:248 lib/gda-client/gda-field.c:251
msgid "<Unknown GDA Type(NULL)>"
msgstr "<Tipo GDA Descoñecido (NULL)>"

#: lib/gda-client/gda-field.c:264
#, fuzzy
msgid "true"
msgstr "Certo"

#: lib/gda-client/gda-field.c:266
#, fuzzy
msgid "false"
msgstr "Falso"

#: lib/gda-common/gda-corba.c:88
#, c-format
msgid "CORBA System exception: %s"
msgstr "Excepción de Sistema de CORBA: %s"

#: lib/gda-common/gda-corba.c:123
msgid "True"
msgstr "Certo"

#: lib/gda-common/gda-corba.c:124
msgid "False"
msgstr "Falso"

#: lib/gda-common/gda-error.c:128
#, c-format
msgid "%s: The server didn't respond."
msgstr "%s: O servidor non respondeu."

#: lib/gda-common/gda-error.c:135
#, c-format
msgid "%s: An Error occured in the CORBA system."
msgstr "%s: Ocorreu un erro no sistema CORBA."

#: lib/gda-common/gda-error.c:152
#, fuzzy
msgid "[CORBA User Exception]"
msgstr "Excepción de usuario de CORBA: %s"

#: lib/gda-common/gda-error.c:201
msgid "Unknown CORBA exception for connection"
msgstr ""

#: lib/gda-common/gda-init.c:55
msgid "Attempt to initialize an already initialized client"
msgstr "Tentouse inicializar un cliente xa inicializado"

#: lib/gda-common/gda-init.c:64 lib/gda-server/gda-server-init.c:121
#, fuzzy
msgid "Could not initialize Bonobo"
msgstr "Non foi posible inicializar ct_diag()"

#: lib/gda-common/gda-log.c:48
msgid "Saving log...x"
msgstr "Gardando rexistro..."

#. compose message
#: lib/gda-common/gda-log.c:68
msgid "ERROR: "
msgstr "ERRO: "

#: lib/gda-common/gda-log.c:68
msgid "MESSAGE: "
msgstr "MENSAXE: "

#: lib/gda-common/gda-thread.c:168
msgid "thread is already running"
msgstr "o fío aínda está en execución"

#: lib/gda-common/gda-util.c:113
#, fuzzy, c-format
msgid "Could not open file %s"
msgstr "Non foi posible establece-lo locale a '%s'"

#: lib/gda-common/gda-util.c:138
#, fuzzy, c-format
msgid "Could not create file %s"
msgstr "non foi posible asignar memoria para o campo"

#: lib/gda-common/gda-xml-database.c:166
msgid "bad formed document"
msgstr ""

#: lib/gda-common/gda-xml-database.c:267
#, c-format
msgid "table %s already exists"
msgstr "a táboa %s xa existe"

#: lib/gda-common/gda-xml-database.c:449
#, c-format
msgid "%p is not a valid table"
msgstr "%p non é unha táboa válida"

#: lib/gda-common/gda-xml-item.c:386
#, fuzzy, c-format
msgid "Item with id %s not found"
msgstr "Fonte de datos %s non atopada"

#: lib/gda-server/gda-server-connection.c:404
#, fuzzy
msgid "Connection being closed"
msgstr "Semella que a conexión está morta"

#: lib/gda-server/gda-server-connection.c:407
msgid "This connection is being closed, so all listeners are released"
msgstr ""

#: lib/gda-server/gda-server-error.c:41
msgid "Could not get pointer to server implementation"
msgstr "Non se pode obte-lo punteiro á implementación do servidor"

#: lib/gda-server/gda-server-init.c:43 lib/gda-server/gda-server-init.c:49
#, c-format
msgid "Received signal %d, shutting down"
msgstr "Recibiuse o sinal %d, saíndo"

#: lib/gda-server/gda-server-init.c:53
#, c-format
msgid "Received signal %d. Ignoring"
msgstr "Recibiuse o sinal %d. Ignorando"

#: lib/gda-server/gda-server-init.c:104
msgid "Attempt to initialize an already initialized provider"
msgstr "Tentouse inicializar un fornecedor xa inicializado"

#: lib/gda-server/gda-server-recordset.c:52
#: lib/gda-server/gda-server-recordset.c:60
#: lib/gda-server/gda-server-recordset.c:100
#: lib/gda-server/gda-server-recordset.c:108
#, c-format
msgid "%s not implemented"
msgstr "%s non implementado"

#: lib/gda-server/gda-server.c:128
#, c-format
msgid "Starting provider %s with no implementation functions"
msgstr "Iniciando o fornecedor %s sen funcións de implementación"

#: lib/gda-server/gda-server.c:214
#, c-format
msgid "CORBA system exception %s"
msgstr "Excepción de sistema de CORBA %s"

#: lib/gda-server/gda-server.c:218
#, c-format
msgid "CORBA user exception: %s"
msgstr "Excepción de usuario de CORBA: %s"

#: providers/gda-default-server/GNOME_GDA_Provider_Default.oaf.in.h:1
#, fuzzy
msgid "Default provider connection factory"
msgstr "non foi posible abrir unha conexión a %s"

#: providers/gda-default-server/GNOME_GDA_Provider_Default.oaf.in.h:2
msgid "GDA Default Datasource Access"
msgstr ""

#: providers/gda-default-server/gda-default-connection.c:127
msgid "You must specify a directory for the database to be stored"
msgstr ""

#: providers/gda-default-server/gda-default-connection.c:235
#: providers/gda-mysql-server/gda-mysql-connection.c:283
#: providers/gda-oracle-server/gda-oracle-connection.c:334
#: providers/gda-postgres-server/gda-postgres-connection.c:486
#, fuzzy
msgid "Unknown schema type"
msgstr "Tipo %ld de ORACLE descoñecido"

#: providers/gda-default-server/main-default.c:70
#, fuzzy
msgid "Could not register Default provider implementation"
msgstr "Non foi posible rexistra-la implementación do fornecedor de correo"

#: providers/gda-ldap-server/GNOME_GDA_Provider_LDAP.oaf.in.h:1
msgid "GDA Datasource Access for LDAP"
msgstr ""

#: providers/gda-ldap-server/GNOME_GDA_Provider_LDAP.oaf.in.h:2
msgid "LDAP provider connection factory"
msgstr ""

#: providers/gda-interbase-server/gda-interbase-connection.c:331
#: providers/gda-ldap-server/gda-ldap-connection.c:293
#: providers/gda-mdb-server/gda-mdb-connection.c:372
#: providers/gda-mysql-server/gda-mysql-connection.c:490
#: providers/gda-odbc-server/gda-odbc-connection.c:624
#: providers/gda-odbc-server/gda-odbc-connection.c:657
#: providers/gda-oracle-server/gda-oracle-connection.c:479
#: providers/gda-postgres-server/gda-postgres-connection.c:767
#: providers/gda-sybase-server/gda-sybase-error.c:132
#: providers/gda-tds-server/gda-tds-error.c:128
#, c-format
msgid "error '%s' at %s"
msgstr "erro '%s' en %s"

#. gda_error_set_help_file (error, _("Not available"));
#: providers/gda-interbase-server/gda-interbase-connection.c:337
#: providers/gda-ldap-server/gda-ldap-connection.c:298
#: providers/gda-ldap-server/gda-ldap-connection.c:299
#: providers/gda-mdb-server/gda-mdb-connection.c:377
#: providers/gda-mysql-server/gda-mysql-connection.c:498
#: providers/gda-mysql-server/gda-mysql-connection.c:499
#: providers/gda-odbc-server/gda-odbc-connection.c:626
#: providers/gda-odbc-server/gda-odbc-connection.c:628
#: providers/gda-odbc-server/gda-odbc-connection.c:659
#: providers/gda-odbc-server/gda-odbc-connection.c:661
#: providers/gda-oracle-server/gda-oracle-connection.c:484
#: providers/gda-oracle-server/gda-oracle-connection.c:485
#: providers/gda-postgres-server/gda-postgres-connection.c:775
#: providers/gda-postgres-server/gda-postgres-connection.c:776
#: providers/gda-primebase-server/gda-primebase-connection.c:375
#: providers/gda-primebase-server/gda-primebase-connection.c:376
#: providers/gda-sybase-server/gda-sybase-error.c:142
#: providers/gda-tds-server/gda-tds-error.c:137
#: providers/gda-tds-server/gda-tds-error.c:138
msgid "Not available"
msgstr "Non dispoñible"

#: providers/gda-interbase-server/gda-interbase-connection.c:338
#: providers/gda-ldap-server/gda-ldap-connection.c:300
#: providers/gda-mdb-server/gda-mdb-connection.c:378
#: providers/gda-mysql-server/gda-mysql-connection.c:500
#: providers/gda-oracle-server/gda-oracle-connection.c:486
#: providers/gda-postgres-server/gda-postgres-connection.c:777
#: providers/gda-primebase-server/gda-primebase-connection.c:377
#: providers/gda-sybase-server/gda-sybase-error.c:143
#: providers/gda-tds-server/gda-tds-error.c:139
msgid "error"
msgstr "erro"

#: providers/gda-ldap-server/main-ldap.c:73
msgid "Could not register LDAP provider implementation"
msgstr "Non foi posible rexistra-la implementación do fornecedor LDAP"

#: providers/gda-interbase-server/GNOME_GDA_Provider_InterBase.oaf.in.h:1
msgid "GDA Datasource Access for Interbase"
msgstr ""

#: providers/gda-interbase-server/GNOME_GDA_Provider_InterBase.oaf.in.h:2
msgid "InterBase provider connection factory"
msgstr ""

#: providers/gda-interbase-server/gda-interbase-connection.c:327
#, fuzzy, c-format
msgid "Error code %ld (%s)"
msgstr "Código de erro %ld"

#: providers/gda-interbase-server/main-interbase.c:74
msgid "Could not register INTERBASE provider implementation"
msgstr "Non foi posible rexistra-la implementación do fornecedor INTERBASE"

#: providers/gda-mail-server/GNOME_GDA_Provider_Mail.oaf.in.h:1
msgid "GDA Datasource Access for Mail"
msgstr ""

#: providers/gda-mail-server/GNOME_GDA_Provider_Mail.oaf.in.h:2
msgid "Mail provider connection factory"
msgstr ""

#: providers/gda-mail-server/gda-mail-connection.c:107
#: providers/gda-mdb-server/gda-mdb-connection.c:224
#: providers/gda-sybase-server/gda-sybase-connection.c:290
#: providers/gda-tds-server/gda-tds-connection.c:283
#, c-format
msgid "Unhandled SCHEMA_QTYPE %d"
msgstr "SCHEMA_QTYPE %d non manexado"

#: providers/gda-mail-server/main-mail.c:74
msgid "Could not register Mail provider implementation"
msgstr "Non foi posible rexistra-la implementación do fornecedor de correo"

#: providers/gda-mdb-server/GNOME_GDA_Provider_MDB.oaf.in.h:1
msgid "GDA Datasource Access for MDB (MS Access) files"
msgstr ""

#: providers/gda-mdb-server/GNOME_GDA_Provider_MDB.oaf.in.h:2
msgid "MDB provider connection factory"
msgstr ""

#. execute command
#: providers/gda-mdb-server/gda-mdb-command.c:86
#: providers/gda-mysql-server/gda-mysql-command.c:144
#: providers/gda-sybase-server/gda-sybase-command.c:141
#: providers/gda-tds-server/gda-tds-command.c:125
#, c-format
msgid "executing command '%s'"
msgstr "executando o comando '%s'"

#: providers/gda-mdb-server/gda-mdb-command.c:88
#: providers/gda-mysql-server/gda-mysql-command.c:149
#, c-format
msgid "info '%s'"
msgstr "info '%s'"

#: providers/gda-mdb-server/gda-mdb-connection.c:137
#, c-format
msgid ""
"%s:%d: You cannot provide a UNIX_SOCKET if you also provide either a HOST or "
"a PORT. Please remove the UNIX_SOCKET, or remove both the HOST and PORT "
"options"
msgstr ""
"%s:%d: Non pode indicar un UNIX_SOCKET se tamén dá unha MÁQUINA ou un PORTO. "
"Quite o UNIX_SOCKET, ou as opcións MÁQUINA e PORTO"

#: providers/gda-mdb-server/gda-mdb-connection.c:147
#, c-format
msgid "%s:%d: You must  provide the filename with the MS Access database"
msgstr "%s:%d: Ten que indica-lo nome do ficheiro coa base de datos MS Access"

#: providers/gda-mdb-server/gda-mdb-connection.c:152
#, c-format
msgid "Opening connection with filename=%s, user=%s, password=%s"
msgstr "Abrindo a conexión con ficheiro=%s, usuario=%s, contrasinal=%s"

#: providers/gda-mdb-server/gda-mdb-connection.c:427
msgid "mysql_recset is NULL"
msgstr "mysql_recset é NULL"

#: providers/gda-mdb-server/gda-mdb-connection.c:469
#: providers/gda-mysql-server/gda-mysql-connection.c:845
#: providers/gda-sybase-server/gda-sybase-connection.c:469
#: providers/gda-tds-server/gda-tds-connection.c:453
msgid "No table name given for SCHEMA_COLS"
msgstr "Non se indicou un nome de táboa para SCHEMA_COLS"

#: providers/gda-mdb-server/main-mdb.c:72
#: providers/gda-mysql-server/main-mysql.c:74
msgid "Could not register MySQL provider implementation"
msgstr "Non foi posible rexistra-la implementación do fornecedor MySQL"

#: providers/gda-mysql-server/GNOME_GDA_Provider_MySQL.oaf.in.h:1
msgid "GDA Datasource Access for MySQL"
msgstr ""

#: providers/gda-mysql-server/GNOME_GDA_Provider_MySQL.oaf.in.h:2
msgid "MySQL provider connection factory"
msgstr ""

#: providers/gda-mysql-server/gda-mysql-connection.c:175
#, fuzzy
msgid ""
"You cannot provide a UNIX_SOCKET if you also provide either a HOST or a "
"PORT. Please remove the UNIX_SOCKET, or remove both the HOST and PORT options"
msgstr ""
"%s:%d: Non pode indicar un UNIX_SOCKET se tamén dá unha MÁQUINA ou un PORTO. "
"Quite o UNIX_SOCKET, ou as opcións MÁQUINA e PORTO"

#: providers/gda-mysql-server/gda-mysql-connection.c:191
#, c-format
msgid ""
"Opening connection with user=%s, password=%s, host=%s, port=%s, unix_socket=%"
"s"
msgstr ""
"Abrindo a conexión con usuario=%s, contrasinal=%s, máquina=%s, porto=%s, "
"unix_socket=%s"

#: providers/gda-mysql-server/gda-mysql-connection.c:623
msgid "Unknown"
msgstr ""

#: providers/gda-mysql-server/gda-mysql-connection.c:656
msgid "No MYSQL_Connection for GdaServerConnection"
msgstr ""

#: providers/gda-odbc-server/GNOME_GDA_Provider_ODBC.oaf.in.h:1
msgid "GDA Datasource Access for ODBC"
msgstr ""

#: providers/gda-odbc-server/GNOME_GDA_Provider_ODBC.oaf.in.h:2
msgid "ODBC provider connection factory"
msgstr ""

#: providers/gda-odbc-server/gda-odbc-connection.c:277
#, c-format
msgid "gda_odbc_connection_open_schema: Unhandled SCHEMA_QTYPE %d\n"
msgstr "gda_odbc_connection_open_schema: SCHEMA_QTYPE %d non manexado\n"

#: providers/gda-odbc-server/gda-odbc-connection.c:641
#: providers/gda-odbc-server/gda-odbc-connection.c:642
#: providers/gda-odbc-server/gda-odbc-connection.c:643
#: providers/gda-odbc-server/gda-odbc-connection.c:674
#: providers/gda-odbc-server/gda-odbc-connection.c:675
#: providers/gda-odbc-server/gda-odbc-connection.c:676
msgid "no text"
msgstr "sen texto"

#: providers/gda-odbc-server/main-odbc.c:73
msgid "Could not register ODBC provider implementation"
msgstr "Non foi posible rexistra-la implementación do fornecedor ODBC"

#: providers/gda-oracle-server/GNOME_GDA_Provider_Oracle.oaf.in.h:1
msgid "GDA Datasource Access for Oracle"
msgstr ""

#: providers/gda-oracle-server/GNOME_GDA_Provider_Oracle.oaf.in.h:2
msgid "Oracle provider connection factory"
msgstr ""

#: providers/gda-oracle-server/gda-oracle-command.c:191
msgid "Could not allocate statement handle"
msgstr "Non foi posible asignar memoria para o manexador da declaración"

#: providers/gda-oracle-server/gda-oracle-command.c:197
msgid "command object being created without associated connection"
msgstr "o obxecto de comando estase a crear sen unha conexión asociada"

#: providers/gda-oracle-server/gda-oracle-command.c:238
#, c-format
msgid "Executing command '%s'"
msgstr "Executando o comando '%s'"

#: providers/gda-oracle-server/gda-oracle-connection.c:117
msgid "error in OCIHandleAlloc() HTYPE_SVCCTX"
msgstr "erro en OCIHandleAlloc() HTYPE_SVCCTX"

#: providers/gda-oracle-server/gda-oracle-connection.c:123
msgid "error in OCIHandleAlloc() HTYPE_SERVER"
msgstr "erro en OCIHandleAlloc() HTYPE_SERVER"

#: providers/gda-oracle-server/gda-oracle-connection.c:129
msgid "error in OCIHandleAlloc() HTYPE_ERROR"
msgstr "erro en OCIHandleAlloc() HTYPE_ERROR"

#: providers/gda-oracle-server/gda-oracle-connection.c:418
#, c-format
msgid "Unknown ORACLE type %ld"
msgstr "Tipo %ld de ORACLE descoñecido"

#: providers/gda-oracle-server/gda-oracle-recordset.c:118
msgid "Unknown ORACLE data type in fill_field_values"
msgstr "Tipo de datos de ORACLE descoñecido en fill_field_values"

#: providers/gda-oracle-server/gda-oracle-recordset.c:156
msgid "recordset object being created without associated connection"
msgstr "o obxecto recordset estase a crear sen ningunha conexión asociada"

#: providers/gda-oracle-server/main-oracle.c:69
msgid "Could not register ORACLE provider implementation"
msgstr "Non foi posible rexistra-la implementación do fornecedor ORACLE"

#: providers/gda-postgres-server/GNOME_GDA_Provider_Postgres.oaf.in.h:1
msgid "GDA Datasource Access for Postgres"
msgstr ""

#: providers/gda-postgres-server/GNOME_GDA_Provider_Postgres.oaf.in.h:2
msgid "Postgres provider connection factory"
msgstr ""

#: providers/gda-postgres-server/gda-postgres-connection.c:888
#: providers/gda-postgres-server/gda-postgres-connection.c:1005
msgid "postgres_recset is NULL"
msgstr "postgres_recset é NULL"

#: providers/gda-postgres-server/main-postgres.c:71
msgid "Could not register PostgreSQL provider implementation"
msgstr "Non foi posible rexistra-la implementación do fornecedor PostgreSQL"

#: providers/gda-sybase-server/GNOME_GDA_Provider_Sybase.oaf.in.h:1
msgid "GDA Datasource Access for Sybase"
msgstr ""

#: providers/gda-sybase-server/GNOME_GDA_Provider_Sybase.oaf.in.h:2
msgid "Sybase provider connection factory"
msgstr ""

#.      gda_server_error_make(error, 0, cnc, "connection seems to be dead");
#: providers/gda-sybase-server/gda-sybase-command.c:136
#: providers/gda-tds-server/gda-tds-command.c:121
msgid "Connection seems to be dead"
msgstr "Semella que a conexión está morta"

#: providers/gda-sybase-server/gda-sybase-command.c:153
#: providers/gda-tds-server/gda-tds-command.c:135
msgid "Filling command structure failed\n"
msgstr "Fallou o enchido da estructura do comando\n"

#: providers/gda-sybase-server/gda-sybase-command.c:162
#: providers/gda-tds-server/gda-tds-command.c:142
msgid "sending cmd failed"
msgstr "fallou o envío do comando"

#: providers/gda-sybase-server/gda-sybase-command.c:169
#: providers/gda-tds-server/gda-tds-command.c:149
msgid "Allocating recordset failed"
msgstr "Fallou a asignación de memoria para o recordset"

#: providers/gda-sybase-server/gda-sybase-command.c:181
#: providers/gda-tds-server/gda-tds-command.c:158
msgid "Getting recordset userdata failed"
msgstr "Fallou a obtención dos datos de usuario do recordset"

#: providers/gda-sybase-server/gda-sybase-command.c:241
#: providers/gda-tds-server/gda-tds-command.c:215
msgid "Command execution finished, all results processed"
msgstr "Execución do comando rematada, procesados tódolos resultados"

#: providers/gda-sybase-server/gda-sybase-command.c:245
#: providers/gda-tds-server/gda-tds-command.c:219
msgid "Command failed"
msgstr "Comando fallido"

#: providers/gda-sybase-server/gda-sybase-command.c:250
#: providers/gda-tds-server/gda-tds-command.c:224
msgid "Execution of resultless command succeeded"
msgstr "Execución correcta dun comando sen resultado"

#: providers/gda-sybase-server/gda-sybase-command.c:268
#: providers/gda-tds-server/gda-tds-command.c:242
#, c-format
msgid "ct_results() returned %x"
msgstr "ct_results() devolveu %x"

#: providers/gda-sybase-server/gda-sybase-command.c:280
#: providers/gda-tds-server/gda-tds-command.c:254
msgid "No further results, command completly succeeded."
msgstr "Non hai máis resultados, o comando completouse correctamente."

#: providers/gda-sybase-server/gda-sybase-command.c:285
#: providers/gda-tds-server/gda-tds-command.c:259
msgid "An error occured during command execution."
msgstr "Ocorreu un erro durante a execución do comando."

#: providers/gda-sybase-server/gda-sybase-command.c:291
#: providers/gda-tds-server/gda-tds-command.c:263
msgid "Cmd execution returned unknown result, may be an error"
msgstr ""
"A execución do comando devolveu un resultado descoñecido, pode que sexa un "
"erro"

#: providers/gda-sybase-server/gda-sybase-command.c:304
#: providers/gda-tds-server/gda-tds-command.c:274
msgid "No data returned, freeing recordset structure"
msgstr "Non se devolveu ningún dato, liberando a estructura recordset"

#: providers/gda-sybase-server/gda-sybase-command.c:336
#: providers/gda-sybase-server/gda-sybase-command.c:348
#: providers/gda-tds-server/gda-tds-command.c:305
#: providers/gda-tds-server/gda-tds-command.c:315
msgid "Freeing command structure failed"
msgstr "Fallou a liberación da estructura do comando"

#: providers/gda-sybase-server/gda-sybase-connection.c:176
msgid "Not enough memory for sybase_Connection"
msgstr "Non hai memoria dabondo para sybase_Connection"

#: providers/gda-sybase-server/gda-sybase-connection.c:458
#: providers/gda-tds-server/gda-tds-connection.c:442
#, c-format
msgid "schema_cols: table_name '%s'"
msgstr "schema_cols: table_name '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:475
#: providers/gda-tds-server/gda-tds-connection.c:459
msgid "Could not allocate command structure"
msgstr "Non foi posible asignar memoria para a estructura de comando"

#: providers/gda-sybase-server/gda-sybase-connection.c:498
#: providers/gda-tds-server/gda-tds-connection.c:482
msgid "Could not allocate enough memory for query"
msgstr "Non foi posible asignar memoria dabondo para a consulta"

#.          gda_server_error_make(error, NULL, cnc, __PRETTY_FUNCTION__);
#: providers/gda-sybase-server/gda-sybase-connection.c:513
#: providers/gda-tds-server/gda-tds-connection.c:497
msgid "Could not get recordset in schema_cols"
msgstr "Non foi posible obte-lo recordset en schema_cols"

#: providers/gda-sybase-server/gda-sybase-connection.c:562
#: providers/gda-tds-server/gda-tds-connection.c:546
#, c-format
msgid "schema_procs: invalid constraint type %d"
msgstr "schema_procs: tipo de restricción %d non válida"

#: providers/gda-sybase-server/gda-sybase-connection.c:572
#: providers/gda-tds-server/gda-tds-connection.c:556
msgid "Could not allocate cmd structure"
msgstr "Non foi posible asignar memoria para a estructura cmd"

#: providers/gda-sybase-server/gda-sybase-connection.c:638
#: providers/gda-tds-server/gda-tds-connection.c:622
#, c-format
msgid "schema_tables: invalid constraint type %d"
msgstr "schema_tables: tipo de restricción %d non válida"

#: providers/gda-sybase-server/gda-sybase-connection.c:700
#: providers/gda-tds-server/gda-tds-connection.c:684
#, c-format
msgid "Invalid or unsupported constraint type: %d"
msgstr "Tipo de restricción non válida ou non soportada: %d"

#: providers/gda-sybase-server/gda-sybase-connection.c:743
#: providers/gda-tds-server/gda-tds-connection.c:727
msgid "Could not allocate GdaServerCommand"
msgstr "Non foi posible asignar memoria para GdaServerCommand"

#: providers/gda-sybase-server/gda-sybase-connection.c:774
#: providers/gda-sybase-server/gda-sybase-connection.c:779
#: providers/gda-tds-server/gda-tds-connection.c:757
#: providers/gda-tds-server/gda-tds-connection.c:762
#, c-format
msgid "connection status: %x"
msgstr "estado da conexión: %x"

#: providers/gda-sybase-server/gda-sybase-connection.c:775
#: providers/gda-tds-server/gda-tds-connection.c:758
#, c-format
msgid "return code: %x"
msgstr "código devolvido: %x"

#: providers/gda-sybase-server/gda-sybase-connection.c:813
#: providers/gda-tds-server/gda-tds-connection.c:793
msgid "attempting reconnection"
msgstr "tentando a reconexión"

#: providers/gda-sybase-server/gda-sybase-connection.c:943
#, c-format
msgid "Reconnected to '%s'"
msgstr "Reonectado a '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:945
#: providers/gda-tds-server/gda-tds-connection.c:895
#, c-format
msgid "Connected to %s"
msgstr "Conectado a %s"

#: providers/gda-sybase-server/gda-sybase-connection.c:957
#: providers/gda-tds-server/gda-tds-connection.c:909
#, c-format
msgid "Selected database '%s'"
msgstr "Seleccionada a base de datos '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:986
#: providers/gda-tds-server/gda-tds-connection.c:935
#, c-format
msgid "%s: Could not allocate cmd structure"
msgstr "%s: Non foi posible asignar memoria para a estructura do comando"

#: providers/gda-sybase-server/gda-sybase-connection.c:995
#: providers/gda-tds-server/gda-tds-connection.c:944
#, c-format
msgid "%s: Could not allocate memory for cmd string"
msgstr "%s: Non foi posible asignar memoria para a cadea do comando"

#: providers/gda-sybase-server/gda-sybase-connection.c:1004
#: providers/gda-tds-server/gda-tds-connection.c:952
#, c-format
msgid "%s: ct_command failed"
msgstr "%s: ct_command fallou"

#: providers/gda-sybase-server/gda-sybase-connection.c:1015
#: providers/gda-tds-server/gda-tds-connection.c:962
#, c-format
msgid "%s: sending command failed"
msgstr "%s: fallou o envío do comando"

#: providers/gda-sybase-server/gda-sybase-connection.c:1026
#, c-format
msgid "%s: selecting database failed"
msgstr "%s: fallou a selección da base de datos"

#: providers/gda-sybase-server/gda-sybase-connection.c:1043
#, c-format
msgid "%s: use command failed"
msgstr "%s: o comando 'use' fallou"

#: providers/gda-sybase-server/gda-sybase-connection.c:1071
#: providers/gda-tds-server/gda-tds-connection.c:1025
msgid "Could not allocate locale structure"
msgstr "Non foi posible asignar memoria para a estructura de locale"

#: providers/gda-sybase-server/gda-sybase-connection.c:1077
#: providers/gda-tds-server/gda-tds-connection.c:1031
#, c-format
msgid "Could not set locale to '%s'"
msgstr "Non foi posible establece-lo locale a '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:1084
#: providers/gda-tds-server/gda-tds-connection.c:1038
#, c-format
msgid "Could not configure locale to be '%s'"
msgstr "Non foi posible configura-lo locale como '%s'"

#: providers/gda-sybase-server/gda-sybase-connection.c:1090
#: providers/gda-tds-server/gda-tds-connection.c:1044
msgid "Could not drop locale structure"
msgstr "Non foi posible libera-la memoria da estructura de locale"

#: providers/gda-sybase-server/gda-sybase-connection.c:1104
#: providers/gda-tds-server/gda-tds-connection.c:1057
#, c-format
msgid "Fatal error: %s\n"
msgstr "Erro moi grave: %s\n"

#: providers/gda-sybase-server/gda-sybase-error.c:78
#, c-format
msgid "gda_sybase_error_make(%p,%p,%p,%p)"
msgstr "gda_sybase_error_make(%p,%p,%p,%p)"

#: providers/gda-sybase-server/gda-sybase-error.c:90
#: providers/gda-tds-server/gda-tds-error.c:86
#, c-format
msgid "No error flag ist set, though %s is called. This may be a bug."
msgstr ""
"Non hai ningunha marca de erro activa, pero chamouse a %s. Isto pode ser un "
"erro no código."

#: providers/gda-sybase-server/gda-sybase-error.c:166
msgid "cs_diag() initialized"
msgstr "cs_diag() inicializado"

#: providers/gda-sybase-server/gda-sybase-error.c:170
msgid "Could not initialize cs_diag()"
msgstr "Non foi posible inicializar cs_diag()"

#: providers/gda-sybase-server/gda-sybase-error.c:180
msgid "ct_diag() initialized"
msgstr "ct_diag() inicializado"

#: providers/gda-sybase-server/gda-sybase-error.c:184
msgid "Could not initialize ct_diag()"
msgstr "Non foi posible inicializar ct_diag()"

#: providers/gda-sybase-server/gda-sybase-error.c:220
#, c-format
msgid "%s could not find server implementation"
msgstr "%s non puido atopa-la implementación do servidor"

#: providers/gda-sybase-server/gda-sybase-error.c:227
#, c-format
msgid "%s could not get cnc userdata"
msgstr "%s non puido obte-los datos de usuario de cnc"

#: providers/gda-sybase-server/gda-sybase-error.c:239
msgid "Could not get # of messages"
msgstr "Non foi posible obte-lo número de mensaxes"

#: providers/gda-sybase-server/gda-sybase-error.c:246
#, c-format
msgid "%d ctlib messages to fetch"
msgstr "%d mensaxes de ctlib para recibir"

#: providers/gda-sybase-server/gda-sybase-error.c:251
#, c-format
msgid "%d ctlib message to fetch"
msgstr "%d mensaxes de ctlib para recibir"

#: providers/gda-sybase-server/gda-sybase-error.c:289
msgid "error is nullpointer in gda_sybase_messages_handle"
msgstr "o erro é un punteiro a null en gda_sybase_messages_handle"

#: providers/gda-sybase-server/gda-sybase-error.c:315
#: providers/gda-sybase-server/gda-sybase-error.c:387
#: providers/gda-sybase-server/gda-sybase-error.c:434
msgid "Could not get # of server messages"
msgstr "Non foi posible obte-lo número de mensaxes de servidor"

#: providers/gda-sybase-server/gda-sybase-error.c:323
#, c-format
msgid "Fetching %d client messages"
msgstr "Recibindo %d mensaxes de cliente"

#: providers/gda-sybase-server/gda-sybase-error.c:326
#, c-format
msgid "Fetching %d client message"
msgstr "Recibindo %d mensaxe de cliente"

#: providers/gda-sybase-server/gda-sybase-error.c:335
#, c-format
msgid "Could not get client msg # %d"
msgstr "Non foi posible obte-la mensaxe de cliente %d"

#: providers/gda-sybase-server/gda-sybase-error.c:354
msgid "Could not get # of client messages"
msgstr "Non foi posible obte-lo número de mensaxes de cliente"

#: providers/gda-sybase-server/gda-sybase-error.c:362
msgid "Could not clear client messages"
msgstr "Non foi posible baleira-las mensaxes de cliente"

#: providers/gda-sybase-server/gda-sybase-error.c:395
#, c-format
msgid "Fetching %d server messages"
msgstr "Recibindo %d mensaxes de servidor"

#: providers/gda-sybase-server/gda-sybase-error.c:398
#, c-format
msgid "Fetching %d server message"
msgstr "Recibindo %d mensaxe de servidor"

#: providers/gda-sybase-server/gda-sybase-error.c:407
#, c-format
msgid "Could not get server msg # %d"
msgstr "Non foi posible recibi-la mensaxe de servidor %d"

#: providers/gda-sybase-server/gda-sybase-error.c:442
msgid "Could not clear server messages"
msgstr "Non foi posible baleira-las mensaxes de servidor"

#: providers/gda-sybase-server/gda-sybase-error.c:464
#: providers/gda-sybase-server/gda-sybase-error.c:504
msgid "Could not get # of cslib messages"
msgstr "Non foi posible obte-lo número de mensaxes de cslib"

#: providers/gda-sybase-server/gda-sybase-error.c:472
#, c-format
msgid "Fetching %d cslib messages"
msgstr "Recibindo %d mensaxes de cslib"

#: providers/gda-sybase-server/gda-sybase-error.c:475
#, fuzzy, c-format
msgid "Fetching %d cslib message"
msgstr "Recibindo %d mensaxes de cslib"

#: providers/gda-sybase-server/gda-sybase-error.c:485
#, c-format
msgid "Could not get cslib msg # %d"
msgstr "Non foi posible recibi-la mensaxe de cslib %d"

#: providers/gda-sybase-server/gda-sybase-error.c:512
msgid "Could not clear cslib messages"
msgstr "Non foi posible baleira-las mensaxes de cslib"

#: providers/gda-sybase-server/gda-sybase-error.c:646
#: providers/gda-tds-server/gda-tds-error.c:274
msgid "Server message:"
msgstr "Mensaxe de servidor:"

#: providers/gda-sybase-server/gda-sybase-error.c:654
#: providers/gda-tds-server/gda-tds-error.c:282
msgid "Client message:"
msgstr "Mensaxe de cliente:"

#: providers/gda-sybase-server/gda-sybase-error.c:661
#: providers/gda-tds-server/gda-tds-error.c:289
msgid "CS-Library error:"
msgstr "Erro de CS-Library:"

#: providers/gda-sybase-server/gda-sybase-recordset.c:203
#: providers/gda-tds-server/gda-tds-recordset.c:199
#, c-format
msgid "fetch error at row %d"
msgstr "erro recibindo na ringleira %d"

#: providers/gda-sybase-server/gda-sybase-recordset.c:210
#: providers/gda-tds-server/gda-tds-recordset.c:206
#, c-format
msgid "CS_END_DATA on row %d; canceling"
msgstr "CS_END_DATA na ringleira %d; cancelando"

#: providers/gda-sybase-server/gda-sybase-recordset.c:218
#: providers/gda-tds-server/gda-tds-recordset.c:213
#, c-format
msgid "%s: Error (%d)"
msgstr "%s: Erro (%d)"

#: providers/gda-sybase-server/gda-sybase-recordset.c:391
#: providers/gda-tds-server/gda-tds-recordset.c:387
msgid "Failed fetching # of columns"
msgstr "Fallou a recepción do número de columnas"

#: providers/gda-sybase-server/gda-sybase-recordset.c:398
#: providers/gda-tds-server/gda-tds-recordset.c:395
#, c-format
msgid "Counted %d columns"
msgstr "Contáronse %d columnas"

#: providers/gda-sybase-server/gda-sybase-recordset.c:405
#: providers/gda-tds-server/gda-tds-recordset.c:402
#, c-format
msgid "%s could not allocate datafmt info"
msgstr "%s non puido asignar memoria para a información do formato de datos"

#: providers/gda-sybase-server/gda-sybase-recordset.c:415
#: providers/gda-tds-server/gda-tds-recordset.c:412
#, c-format
msgid "%s could not allocate data fields"
msgstr "%s non puido asignar memoria para os campos de datos"

#: providers/gda-sybase-server/gda-sybase-recordset.c:433
#: providers/gda-tds-server/gda-tds-recordset.c:430
#, c-format
msgid "ct_describe on col # %d"
msgstr "ct_describe na columna %d"

#: providers/gda-sybase-server/gda-sybase-recordset.c:440
#: providers/gda-tds-server/gda-tds-recordset.c:437
#, c-format
msgid "ct_describe on col # %d failed"
msgstr "ct_describe na columna %d fallou"

#: providers/gda-sybase-server/gda-sybase-recordset.c:447
#: providers/gda-tds-server/gda-tds-recordset.c:444
#, c-format
msgid "ct_describe(%d): '%s', %d (%s)"
msgstr "ct_describe(%d): '%s', %d (%s)"

#: providers/gda-sybase-server/gda-sybase-recordset.c:459
#: providers/gda-tds-server/gda-tds-recordset.c:455
msgid "could not allocate data holder"
msgstr "non foi posible asignar memoria para o almacenador de datos"

#: providers/gda-sybase-server/gda-sybase-recordset.c:472
#: providers/gda-tds-server/gda-tds-recordset.c:468
msgid "could not ct_bind data holder to column"
msgstr "non foi posible asignar con ct_bind o almacenador de datos á columna"

#: providers/gda-sybase-server/gda-sybase-recordset.c:479
#: providers/gda-tds-server/gda-tds-recordset.c:475
msgid "illegal type detected, aborting"
msgstr "tipo ilegal detectado, abortando"

#: providers/gda-sybase-server/gda-sybase-recordset.c:486
#: providers/gda-tds-server/gda-tds-recordset.c:482
msgid "could not allocate field"
msgstr "non foi posible asignar memoria para o campo"

#: providers/gda-sybase-server/main-sybase.c:78
msgid "Could not register gda-sybase provider implementation"
msgstr "Non foi posible rexistra-la implementación do fornecedor gda-sybase"

#: providers/gda-primebase-server/GNOME_GDA_Provider_Primebase.oaf.in.h:1
msgid "GDA Datasource Access for primebase"
msgstr ""

#: providers/gda-primebase-server/gda-primebase-connection.c:157
#, fuzzy, c-format
msgid "Could not connect to '%s@%s:%s' with connparm '%s'"
msgstr "non foi posible abrir unha conexión a %s"

#: providers/gda-primebase-server/gda-primebase-connection.c:163
#, c-format
msgid "%2ld: Connected to '%s@%s:%s' with connparm: '%s'"
msgstr ""

#: providers/gda-primebase-server/gda-primebase-connection.c:171
msgid "Could not get PBIConnectionInfo(), disconnecting"
msgstr ""

#: providers/gda-primebase-server/gda-primebase-connection.c:176
#, c-format
msgid "%2ld: ConInfo: '%s@%s', Cl v%x, Srv '%s' v%x, Brand '%s'"
msgstr ""

#: providers/gda-primebase-server/gda-primebase-connection.c:390
#, fuzzy
msgid "Not enough memory for primebase_Error structure."
msgstr "Non hai memoria dabondo para sybase_Connection"

#: providers/gda-primebase-server/gda-primebase-connection.c:397
#, c-format
msgid "%2ld: ERROR: %ld (%ld) : %s.\n"
msgstr ""

#: providers/gda-primebase-server/main-primebase.c:73
#, fuzzy
msgid "Could not register PRIMEBASE provider implementation"
msgstr "Non foi posible rexistra-la implementación do fornecedor INTERBASE"

#: providers/gda-tds-server/GNOME_GDA_Provider_TDS.oaf.in.h:1
msgid "GDA Datasource Access for Sybase/MS SQL"
msgstr ""

#: providers/gda-tds-server/GNOME_GDA_Provider_TDS.oaf.in.h:2
msgid "TDS provider connection factory"
msgstr ""

#: providers/gda-tds-server/gda-tds-connection.c:165
#, fuzzy
msgid "Not enough memory for tds_Connection"
msgstr "Non hai memoria dabondo para sybase_Connection"

#. Fixme: replace "dummy" with buf when CS_GET CS_SERVERNAME works
#: providers/gda-tds-server/gda-tds-connection.c:893
#, fuzzy, c-format
msgid "Reconnected to %s"
msgstr "Reonectado a '%s'"

#: providers/gda-tds-server/gda-tds-error.c:75
#, fuzzy, c-format
msgid "gda_tds_error_make(%p,%p,%p,%p)"
msgstr "gda_sybase_error_make(%p,%p,%p,%p)"

#: providers/gda-tds-server/main-tds.c:78
#, fuzzy
msgid "Could not register gda-tds provider implementation"
msgstr "Non foi posible rexistra-la implementación do fornecedor gda-sybase"

#: tools/gda-run.c:109
#, c-format
msgid "%s: misconfigured DSN entry"
msgstr "%s: entrada DSN mal configurada"

#: tools/gda-run.c:124
#, c-format
msgid "%s: data source '%s' not found\n"
msgstr "%s: fonte de datos '%s' non atopada\n"

#: tools/templates/main-srv.c.tmpl:60
#, fuzzy
msgid "Could not register <PROVIDER-NAME> provider implementation"
msgstr "Non foi posible rexistra-la implementación do fornecedor INTERBASE"

#~ msgid "TRUE"
#~ msgstr "CERTO"

#~ msgid "FALSE"
#~ msgstr "FALSO"

#~ msgid "impl_GDA_Connection_open: opening connection with DSN: %s"
#~ msgstr "impl_GDA_Connection_open: abrindo a conexión co DSN: %s"

#~ msgid "%s: an error ocurred while fetching data"
#~ msgstr "%s: ocorreu un erro recibindo os datos"

#~ msgid ""
#~ "OAF doesn't know about our IID; indicates broken installation. Exiting..."
#~ msgstr ""
#~ "OAF descoñece o noso IID; isto indica unha instalación errónea. Saíndo..."

#~ msgid ""
#~ "Another instance of this provider is already registered with OAF. "
#~ "Exiting..."
#~ msgstr ""
#~ "Xa hai rexistrada outra instancia deste fornecedor con OAF. Saíndo..."

#~ msgid "Unknown error registering this provider with OAF. Exiting"
#~ msgstr "Erro descoñecido rexistrando este fornecedor con OAF. Saíndo"

#~ msgid "Registered with ID = %s"
#~ msgstr "Rexistrado co ID = %s"

#~ msgid "CORBA exception unloading report engine: %s"
#~ msgstr "Excepción de CORBA o descargar o motor de informes: %s"

#~ msgid "Received signal %d, shutting down."
#~ msgstr "Recibiuse o sinal %d, saíndo."

#~ msgid "Received signal %d, shutting down cleanly"
#~ msgstr "Recibiuse o sinal %d, saíndo limpamente"

#~ msgid "Failed to initialize OAF: please mail bug report to OAF maintainers"
#~ msgstr ""
#~ "Fallo ó inicializar OAF: por favor, envíe un informe do erro ós "
#~ "encargados do OAF"

#~ msgid "Could not activate report engine"
#~ msgstr "Non foi posible activa-lo motor de informes"

#~ msgid ""
#~ "Another instance of the report engine is already registered with OAF. "
#~ "Exiting..."
#~ msgstr ""
#~ "Xa hai rexistrada outra instancia do motor de informes con OAF. Saíndo..."

#~ msgid "Unknown error registering report engine with OAF. Exiting"
#~ msgstr "Erro descoñecido rexistrando o motor de informes con OAF. Saíndo"

#~ msgid "Registered report engine with ID = %s"
#~ msgstr "Rexistrado o motor de informes co ID = %s"

#~ msgid "%s: length = %d"
#~ msgstr "%s: lonxitude = %d"

#~ msgid "%s: sending field description for '%s'"
#~ msgstr "%s: enviando a descrición do campo '%s'"

#~ msgid "Error allocating error structure"
#~ msgstr "Erro asignando memoria para a estructura de erro"

#~ msgid "schema_tables: table name = '%s'"
#~ msgstr "schema_tables: table name = '%s'"

#~ msgid "schema_tables: table_schema = '%s'"
#~ msgstr "schema_tables: table_schema = '%s'"

#~ msgid "schema_procedures: proc_catalog = '%s' UNUSED!\n"
#~ msgstr "schema_procedures: proc_catalog = '%s' ¡SEN USAR!\n"

#~ msgid "schema_procedures: proc_catalog = '%s' UNUSED!"
#~ msgstr "schema_procedures: proc_catalog = '%s' ¡SEN USAR!"

#~ msgid "database name"
#~ msgstr "nome da base de datos"

#~ msgid "DATABASE"
#~ msgstr "BASE-DE-DATOS"

#~ msgid "user name"
#~ msgstr "nome de usuario"

#~ msgid "USER-NAME"
#~ msgstr "NOME-DE-USUARIO"

#~ msgid "password"
#~ msgstr "contrasinal"

#~ msgid "PASSWORD"
#~ msgstr "CONTRASINAL"

#~ msgid "file name"
#~ msgstr "nome do ficheiro"

#~ msgid "FILE-NAME"
#~ msgstr "NOME-DO-FICHEIRO"

#~ msgid "Fetchong %d cslib message"
#~ msgstr "Recibindo %d mensaxe de cslib"

#~ msgid "%s: not implemented"
#~ msgstr "%s: non implementado"
